Repository pyro-ppl/numpyro, pull requests merged in 2019-07, with the labels that each got.

#229 add pairwise interaction analysis to sparse_regression
  examples/sparse_regression.py
Labels: awaiting review

#232 add posterior sampling logic to sparse_regression
  examples/sparse_regression.py
Labels: awaiting review

#228 Remove laxtuple
  examples/vae.py
  numpyro/hmc_util.py
  numpyro/mcmc.py
  numpyro/util.py
Labels: awaiting review, enhancement

#233 add permute transform
  numpyro/distributions/constraints.py
  numpyro/distributions/continuous.py
  numpyro/distributions/distribution.py
  numpyro/distributions/util.py
  test/test_distributions.py
Labels: awaiting review

#239 Use intermediate values for TransformedDistribution.log_prob
  numpyro/distributions/distribution.py
  numpyro/handlers.py
  numpyro/infer_util.py
  test/test_distributions.py
Labels: discussion

#234 Revise IAF transform
  examples/sparse_regression.py
  numpyro/contrib/nn/auto_reg_nn.py
  numpyro/contrib/nn/masked_dense.py
  numpyro/distributions/__init__.py
  numpyro/distributions/constraints.py
  numpyro/distributions/distribution.py
  numpyro/distributions/flows.py
  numpyro/distributions/util.py
  test/contrib/test_auto_regressive_nn.py
  test/test_distributions.py
  test/test_flows.py
  test/test_iaf.py
Labels: awaiting review

#244 Resive summary format to match pyro summary
  numpyro/diagnostics.py
  numpyro/mcmc.py
Labels: awaiting review, easy

#224 add IAF autoguide
  .gitignore
  numpyro/contrib/autoguide/__init__.py
  test/contrib/test_autoguide.py
Labels: awaiting review

#246 Remove some gross in arn and iaf
  numpyro/contrib/autoguide/__init__.py
  numpyro/contrib/nn/auto_reg_nn.py
  numpyro/distributions/flows.py
  numpyro/distributions/util.py
  test/contrib/test_auto_regressive_nn.py
  test/test_flows.py
Labels: awaiting review

#250 Fix nan during step size adaptation
  numpyro/hmc_util.py
Labels: discussion

#253 Fix stepsize getting `nan`
  numpyro/hmc_util.py
Labels: awaiting review

#248 Add an example for NeuTra HMC
  examples/neutra.py
  numpyro/contrib/autoguide/__init__.py
  numpyro/distributions/constraints.py
Labels: awaiting review

#255 Make scale take in a callable fn to scale all sample sites at once
  numpyro/handlers.py
  test/test_handlers.py
Labels: awaiting review, easy

#258 Fix transformed PE function in NeutraHMC
  examples/neutra.py
  numpyro/contrib/autoguide/__init__.py
  numpyro/infer_util.py
Labels: awaiting review, discussion

#260 Simplify and refactor autoguide code for additional flexibility
  numpyro/contrib/autoguide/__init__.py
  numpyro/handlers.py
  test/contrib/test_autoguide.py
  test/test_handlers.py
Labels: awaiting review, discussion

#262 Add condition handler
  numpyro/handlers.py
  test/test_handlers.py
Labels: awaiting review, easy

#247 Implement consensus MC and parametric MC algorithms
  docs/source/mcmc.rst
  numpyro/hmc_util.py
  test/test_hmc_util.py
Labels: awaiting review

#264 Fix the slowness of lax.fori_loop
  examples/minipyro.py
  numpyro/mcmc.py
  numpyro/util.py
  test/contrib/test_autoguide.py
  test/test_example_utils.py
  test/test_hmc_util.py
  test/test_svi.py
Labels: awaiting review

#263 Fix some issues related to reuse rngs
  examples/minipyro.py
  examples/vae.py
  numpyro/handlers.py
  numpyro/hmc_util.py
  numpyro/svi.py
  test/test_svi.py
Labels: awaiting review

#267 Implement ravel_pytree for internal usage
  numpyro/util.py
  test/test_util.py
Labels: awaiting review

#268 Update travis to use JAX master
  .travis.yml
  examples/neutra.py
  numpyro/distributions/continuous.py
  numpyro/distributions/util.py
  setup.py
  test/contrib/test_autoguide.py
Labels: awaiting review

#265 Handling dynamic support
  numpyro/contrib/autoguide/__init__.py
  numpyro/distributions/distribution.py
  numpyro/handlers.py
  numpyro/hmc_util.py
  numpyro/infer_util.py
  test/test_distributions.py
  test/test_hmc_util.py
  test/test_mcmc.py
Labels: awaiting review

#270 Convert TruncatedCauchy, TruncatedNormal, Uniform to transformed distribution
  numpyro/distributions/continuous.py
  test/test_distributions.py
  test/test_hmc_util.py
  test/test_mcmc.py
Labels: awaiting review

#271 dynamic support for improper prior
  numpyro/handlers.py
  numpyro/hmc_util.py
  test/test_mcmc.py
Labels: awaiting review
