Repository pyro-ppl/numpyro, pull requests merged in 2019-09, with the labels that each got.

#318 Add SVI class interface
  docs/source/handlers.rst
  docs/source/svi.rst
  examples/minipyro.py
  examples/neutra.py
  examples/vae.py
  numpyro/contrib/autoguide/__init__.py
  numpyro/handlers.py
  numpyro/svi.py
  test/contrib/test_autoguide.py
  test/test_svi.py
Labels: awaiting review

#315 Add test for vmap
  numpyro/contrib/autoguide/__init__.py
  numpyro/mcmc.py
  setup.py
  test/test_mcmc.py
  test/test_mcmc_interface.py
Labels: awaiting review

#320 Add predictive utility
  numpyro/infer_util.py
  test/test_infer_util.py
Labels: awaiting review

#323 Update Cloudfront link for the new S3 bucket
  numpyro/examples/datasets.py
Labels: awaiting review, easy

#322 add predictive utility to docs
  docs/source/utilities.rst
  notebooks/source/time_series_forecasting.ipynb
Labels: awaiting review, easy

#324 Do not call random.split when sample site is observed
  numpyro/handlers.py
  numpyro/infer_util.py
  test/test_handlers.py
Labels: awaiting review, easy

#327 fix broken link and add missing tutorials
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/index.rst
Labels: easy

#330 Add diverging diagnostics
  numpyro/mcmc.py
  test/test_mcmc_interface.py
Labels: awaiting review

#328 Bump to version 0.2
  docs/source/distributions.rst
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/minipyro.py
  examples/neutra.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/version.py
  setup.py
Labels: awaiting review

#332 Fix issue of finding_initial_params when prior has sample shape kwarg
  numpyro/infer_util.py
  test/test_mcmc_interface.py
Labels: awaiting review

#334 move rng_seed out of svi
  numpyro/svi.py
Labels: awaiting review

#335 Using vectorized Elbo in minipyro example
  examples/minipyro.py
Labels: awaiting review, easy

#336 Add a simplified plate context manager
  docs/source/primitives.rst
  numpyro/__init__.py
  numpyro/handlers.py
  numpyro/infer_util.py
  numpyro/primitives.py
  test/test_handlers.py
Labels: awaiting review

#342 Add a note for sample primitive
  numpyro/primitives.py
Labels: awaiting review

#344 Add compatibility module for pyro.generic
  numpyro/compat/__init__.py
  numpyro/compat/distributions.py
  numpyro/compat/handlers.py
  numpyro/compat/infer.py
  numpyro/compat/pyro.py
  numpyro/handlers.py
  numpyro/mcmc.py
Labels: awaiting review, discussion

#347 Upgrade minimum jax versions to run examples
  setup.py
Labels: awaiting review, easy

#345 use fori + vmap instead of vmap + fori for vectorized method
  numpyro/hmc_util.py
  numpyro/mcmc.py
  numpyro/util.py
  test/test_mcmc_interface.py
Labels: awaiting review

#350 Allow seed handler to be used as a context manager
  numpyro/handlers.py
  test/test_handlers.py
Labels: awaiting review

#348 Fix the bug of computing transformed potential energy in neutra example
  examples/neutra.py
  numpyro/contrib/autoguide/__init__.py
  numpyro/distributions/constraints.py
  numpyro/handlers.py
  numpyro/infer_util.py
  test/contrib/test_autoguide.py
  test/test_distributions.py
  test/test_infer_util.py
Labels: awaiting review

#352 let mcmc run with empty latent sites
  numpyro/hmc_util.py
  numpyro/mcmc.py
  numpyro/util.py
  test/test_mcmc_interface.py
Labels: awaiting review

#358 fix a typo at doc title
  docs/source/index.rst
Labels: awaiting review, easy

#353 Support for prior predictive
  numpyro/infer_util.py
  numpyro/primitives.py
  test/test_infer_util.py
Labels: awaiting review

#356 Fix plate behavior for distributions with batch shape
  numpyro/primitives.py
  test/test_handlers.py
  test/test_infer_util.py
Labels: awaiting review

#359 Add mv affine transform
  docs/source/distributions.rst
  numpyro/distributions/constraints.py
  test/test_distributions.py
Labels: awaiting review

#360 Add to_event to Distribution to change batch-event dim boundary
  numpyro/distributions/__init__.py
  numpyro/distributions/distribution.py
  test/test_distributions.py
Labels: awaiting review

#354 Implement log likelihood and update baseball example
  examples/baseball.py
  numpyro/infer_util.py
  numpyro/mcmc.py
  test/test_infer_util.py
Labels: awaiting review

#367 Remove duplicate MCMC tests for deprecated interfaces
  .travis.yml
  examples/baseball.py
  test/test_handlers.py
  test/test_mcmc.py
Labels: awaiting review, easy

#366 Add documentation for Independent
  docs/source/distributions.rst
  numpyro/contrib/autoguide/__init__.py
  numpyro/distributions/distribution.py
Labels: awaiting review, easy

#365 Improving testing time
  .travis.yml
  test/contrib/test_autoguide.py
  test/contrib/test_distributions_contrib.py
  test/contrib/test_masked_dense.py
  test/contrib/test_nn.py
  test/test_distributions.py
  test/test_distributions_util.py
  test/test_example_utils.py
  test/test_hmc_util.py
  test/test_infer_util.py
  test/test_mcmc.py
  test/test_mcmc_interface.py
Labels: awaiting review

#368 Implement inverse Cholesky transform
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/constraints.py
  numpyro/distributions/continuous.py
  test/test_distributions.py
Labels: awaiting review

#369 Expose energy for bfmi diagnostic
  numpyro/hmc_util.py
  numpyro/mcmc.py
  test/test_mcmc.py
Labels: awaiting review
