Repository pyro-ppl/numpyro, pull requests merged in 2019-12, with the labels that each got.

#480 Separating compiling, warmup phases
  numpyro/infer/mcmc.py
  numpyro/util.py
  test/test_mcmc.py
  test/test_util.py
Labels: awaiting review

#471 add option to add custom thumbnail images
  notebooks/source/conf.py
Labels: awaiting review, low priority

#482 update covtype data file
  numpyro/examples/datasets.py
Labels: awaiting review

#486 Fix progbar description when warmup / sample are run separately
  numpyro/infer/mcmc.py
Labels: awaiting review, easy

#487 Minor changes to infer.util for 0.2.2
  examples/stochastic_volatility.py
  numpyro/contrib/autoguide/__init__.py
  numpyro/infer/mcmc.py
  numpyro/infer/util.py
  test/test_infer_util.py
  test/test_mcmc.py
Labels: awaiting review

#488 Bump up version to 0.2.2
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/minipyro.py
  examples/neutra.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/version.py
  setup.py
Labels: awaiting review

#490 Release patch for python 3.7 incompatibility
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/minipyro.py
  examples/neutra.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/infer/mcmc.py
  numpyro/util.py
  numpyro/version.py
Labels: awaiting review, bug

#495 resolve overflow issue of poisson sampler
  numpyro/distributions/util.py
  test/test_distributions_util.py
Labels: awaiting review, low priority

#500 Deprecate Predictive.get_samples method
  examples/baseball.py
  examples/ucbadmit.py
  notebooks/source/bayesian_regression.ipynb
  numpyro/infer/util.py
  test/test_infer_util.py
Labels: awaiting review, easy

#501 Update docs requirements to fix readthedocs build
  docs/requirements.txt
Labels: awaiting review, easy

#502 Downgrade numpy version in setup and docs build
  docs/requirements.txt
  setup.py
Labels: awaiting review
