Repository pyro-ppl/numpyro, pull requests merged in 2019-11, with the labels that each got.

#430 Update README.md
  README.md
Labels: awaiting review

#431 Minor tweaks
  README.md
  numpyro/infer/mcmc.py
  numpyro/infer/util.py
  numpyro/optim.py
Labels: awaiting review

#433 add diverging to `extra_fields` by default
  README.md
  docs/source/diagnostics.rst
  examples/neutra.py
  numpyro/diagnostics.py
  numpyro/infer/mcmc.py
Labels: awaiting review

#435 Bump up version to 0.2.1
  .travis.yml
  README.md
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/minipyro.py
  examples/neutra.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/infer/mcmc.py
  numpyro/version.py
  setup.py
Labels: awaiting review

#436 Minor edits to README.md
  README.md
Labels: awaiting review

#437 Update tutorial documentation to v0.2.1
  docs/source/conf.py
  notebooks/source/_static/img/pyro_logo_wide.png
  notebooks/source/conf.py
Labels: awaiting review

#439 Remove unused argument from hmc function
  numpyro/infer/mcmc.py
  test/test_mcmc.py
Labels: awaiting review, easy

#443 fix bnn example
  examples/bnn.py
Labels: awaiting review, easy

#442 make sure to use new sample_fn for new data
  numpyro/infer/mcmc.py
  test/test_mcmc.py
Labels: awaiting review

#444 expose inverse_mass_matrix to hmc interface
  numpyro/infer/mcmc.py
Labels: awaiting review, easy

#446 print summary before reporting elapsed time
  examples/bnn.py
  examples/covtype.py
  examples/gp.py
  examples/hmm.py
  examples/sparse_regression.py
Labels: awaiting review, easy

#450 add factor primitive
  docs/source/distributions.rst
  docs/source/primitives.rst
  examples/hmm.py
  numpyro/__init__.py
  numpyro/distributions/__init__.py
  numpyro/distributions/distribution.py
  numpyro/primitives.py
  test/test_distributions.py
Labels: awaiting review

#451 Make it possible to JIT compile model args/kwargs
  numpyro/contrib/autoguide/__init__.py
  numpyro/infer/mcmc.py
  numpyro/infer/util.py
  test/test_infer_util.py
  test/test_mcmc.py
Labels: awaiting review, discussion

#457 Fix docs build in travis
  docs/source/distributions.rst
  numpyro/primitives.py
Labels: awaiting review, easy

#455 Misc refactoring for mcmc util functions
  .travis.yml
  numpyro/infer/util.py
  test/test_mcmc.py
Labels: awaiting review

#459 Add thumbnail images to examples
  .gitignore
  docs/Makefile
  examples/README.rst
  examples/baseball.py
  examples/bnn.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/neutra.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/Makefile
  notebooks/source/_static/css/pyro.css
  notebooks/source/baseball.rst
  notebooks/source/bnn.rst
  notebooks/source/conf.py
  notebooks/source/funnel.rst
  notebooks/source/gp.rst
  notebooks/source/hmm.rst
  notebooks/source/index.rst
  notebooks/source/minipyro.rst
  notebooks/source/sparse_regression.rst
  notebooks/source/stochastic_volatility.rst
  notebooks/source/ucbadmit.rst
  notebooks/source/vae.rst
  setup.cfg
  setup.py
Labels: awaiting review

#456 Ability to reuse compiled assets in MCMC
  numpyro/infer/mcmc.py
  test/test_mcmc.py
Labels: awaiting review

#468 separate summary logic out of print_summary
  .gitignore
  docs/source/diagnostics.rst
  docs/source/primitives.rst
  numpyro/diagnostics.py
  test/test_mcmc.py
Labels: awaiting review

#469 Ability to start MCMC sampling from the same warmup state
  numpyro/infer/mcmc.py
  numpyro/util.py
  test/test_mcmc.py
Labels: WIP

#473 Enable x64 tests in travis
  .travis.yml
  docs/source/utilities.rst
  numpyro/__init__.py
  numpyro/infer/mcmc.py
  numpyro/util.py
  test/test_mcmc.py
Labels: awaiting review, easy

#474 Fix get_potential_fn for dynamic args
  numpyro/infer/util.py
  test/test_mcmc.py
Labels: awaiting review

#476 Fix bug in fori_collect for init val collection
  numpyro/util.py
  test/test_util.py
Labels: awaiting review

#477 Avoid double compiling issue
  numpyro/infer/mcmc.py
Labels: awaiting review

#479 Cache compilation when progbar=False
  numpyro/infer/mcmc.py
  numpyro/util.py
  test/test_mcmc.py
Labels: awaiting review
