Repository pyro-ppl/numpyro, pull requests merged in 2019-05, with the labels that each got.

#131 Test some edge examples from Pyro
  numpyro/contrib/distributions/distribution.py
  numpyro/distributions/constraints.py
  numpyro/distributions/discrete.py
  test/test_distributions.py
  test/test_distributions_contrib.py
  test/test_mcmc.py
Labels: awaiting review

#132 Make utilities work for the newer version of JAX
  numpyro/contrib/distributions/multivariate.py
  numpyro/distributions/discrete.py
  numpyro/distributions/util.py
  test/test_distributions.py
  test/test_distributions_util.py
Labels: awaiting review

#133 Add baseball example in numpyro
  numpyro/examples/baseball.py
  numpyro/examples/datasets.py
  numpyro/examples/vae.py
  test/test_example_utils.py
Labels: awaiting review

#136 Update to newer jax version
  .travis.yml
  numpyro/distributions/continuous.py
  numpyro/examples/minipyro.py
  numpyro/examples/vae.py
  numpyro/patch.py
  numpyro/svi.py
  numpyro/util.py
  setup.py
  test/test_distributions.py
  test/test_mcmc.py
  test/test_optimizers.py
  test/test_util.py
Labels: awaiting review

#137 Update README.md to include build information
  README.md
Labels: awaiting review, easy

#135 Add LKJ distribution and UCBadmit example
  numpyro/distributions/__init__.py
  numpyro/distributions/constraints.py
  numpyro/distributions/continuous.py
  numpyro/distributions/util.py
  numpyro/examples/baseball.py
  numpyro/examples/covtype.py
  numpyro/examples/datasets.py
  numpyro/examples/ucbadmit.py
  test/test_distributions.py
Labels: awaiting review

#138 Add sphinx and rtd support for Numpyro
  .gitignore
  Makefile
  docs/Makefile
  docs/requirements.txt
  docs/source/conf.py
  docs/source/distributions.rst
  docs/source/handlers.rst
  docs/source/index.rst
  docs/source/mcmc.rst
  docs/source/svi.rst
  numpyro/mcmc.py
  setup.py
Labels: awaiting review

#140 Modify HMC documentation to show docstrings for internal functions
  .gitignore
  numpyro/mcmc.py
Labels: awaiting review

#141 Unifying wrappers for distributions with logits/probs parametrization
  numpyro/distributions/__init__.py
  numpyro/distributions/discrete.py
  numpyro/examples/baseball.py
  numpyro/examples/covtype.py
  numpyro/examples/ucbadmit.py
  test/test_distributions.py
  test/test_mcmc.py
Labels: awaiting review, easy

#143 Add stochastic volatility model to examples
  numpyro/distributions/__init__.py
  numpyro/distributions/continuous.py
  numpyro/examples/datasets.py
  numpyro/examples/stochastic_volatility.py
  setup.py
  test/test_distributions.py
  test/test_example_utils.py
Labels: awaiting review

#147 Update to newer version of JAX
  numpyro/distributions/continuous.py
  numpyro/distributions/util.py
  numpyro/examples/baseball.py
  numpyro/examples/covtype.py
  numpyro/examples/ucbadmit.py
  setup.py
  test/test_distributions.py
Labels: awaiting review

#151 Test examples in travis CI
  .gitignore
  .travis.yml
  examples/__init__.py
  examples/baseball.py
  examples/covtype.py
  examples/minipyro.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  examples/vae.py
  numpyro/distributions/continuous.py
  numpyro/examples/datasets.py
  numpyro/hmc_util.py
  setup.py
  test/test_example_utils.py
  test/test_examples.py
  test/test_mcmc.py
Labels: awaiting review, easy

#117 Benchmark numpyro on semisupervised hmm model
  examples/hmm.py
  test/test_examples.py
Labels: awaiting review

#155 fix bug at constraint
  numpyro/distributions/constraints.py
Labels: awaiting review

#157 Adding some more documentation
  Makefile
  docs/source/conf.py
  docs/source/mcmc.rst
  docs/source/svi.rst
  examples/baseball.py
  numpyro/hmc_util.py
  numpyro/mcmc.py
  numpyro/svi.py
Labels: awaiting review

#158 improve precision for constraint's logdet
  numpyro/distributions/constraints.py
Labels: awaiting review

#156 Implement summary stats/diagnostics
  examples/covtype.py
  examples/hmm.py
  numpyro/diagnostics.py
  numpyro/mcmc.py
  test/test_diagnostics.py
  test/test_distributions.py
  test/test_mcmc.py
Labels: awaiting review

#161 make HMCState pickable
  numpyro/mcmc.py
Labels: awaiting review

#162 Change parameters initialization to Uniform(-2, 2)
  numpyro/diagnostics.py
  numpyro/hmc_util.py
  test/test_mcmc.py
Labels: awaiting review, easy

#163 Add diagnostic information to progress bar
  .travis.yml
  docs/source/conf.py
  docs/source/mcmc.rst
  examples/baseball.py
  numpyro/mcmc.py
  numpyro/util.py
  test/test_mcmc.py
Labels: awaiting review, discussion

#165 Use default support in transformed distributions
  numpyro/distributions/constraints.py
  numpyro/distributions/continuous.py
  numpyro/distributions/distribution.py
  numpyro/mcmc.py
  test/conftest.py
  test/test_examples.py
  test/test_mcmc.py
Labels: awaiting review

#166 add bayesian neural network example
  examples/bnn.py
  test/test_examples.py
Labels: awaiting review

#167 add batching rule for standard_gamma
  numpyro/diagnostics.py
  numpyro/distributions/continuous.py
  numpyro/distributions/util.py
  test/test_distributions_util.py
Labels: awaiting review

#119 Add local global trend notebook
  notebooks/time_series_forecasting.ipynb
  numpyro/distributions/discrete.py
  numpyro/distributions/util.py
  numpyro/mcmc.py
  numpyro/util.py
Labels: awaiting review

#170 Implement dense mass matrix adaptation
  .gitignore
  docs/source/diagnostics.rst
  docs/source/index.rst
  numpyro/diagnostics.py
  numpyro/hmc_util.py
  numpyro/mcmc.py
  test/test_hmc_util.py
  test/test_mcmc.py
Labels: awaiting review

#168 Add pathwise tests for some samplers
  test/test_distributions.py
Labels: awaiting review

#172 update hmm and ucbadmit with new api
  examples/hmm.py
  examples/ucbadmit.py
Labels: awaiting review

#60 a pass of hmc docs and comments
  notebooks/time_series_forecasting.ipynb
  numpyro/diagnostics.py
  numpyro/hmc_util.py
  numpyro/mcmc.py
Labels: awaiting review

#171 Add basic tutorial on bayesian regression
  notebooks/bayesian_regression.ipynb
Labels: awaiting review

#174 fix typo in bnn example
  examples/bnn.py
Labels: awaiting review

#173 Change README.md to reflect current status of the project
  README.md
Labels: awaiting review

#178 Add batching rule for some custom primitives
  examples/ucbadmit.py
  numpyro/distributions/util.py
  test/test_distributions_util.py
Labels: awaiting review

#175 Update logistic regression notebook
  notebooks/logistic_regression.ipynb
Labels: awaiting review

#180 Minor pending fixes
  README.md
  notebooks/bayesian_regression.ipynb
  notebooks/logistic_regression.ipynb
  notebooks/time_series_forecasting.ipynb
Labels: awaiting review

#179 Add docs for handlers and distributions
  docs/source/diagnostics.rst
  docs/source/distributions.rst
  docs/source/handlers.rst
  docs/source/index.rst
  docs/source/mcmc.rst
  docs/source/svi.rst
  examples/hmm.py
  notebooks/bayesian_regression.ipynb
  numpyro/diagnostics.py
  numpyro/distributions/continuous.py
  numpyro/distributions/discrete.py
  numpyro/distributions/distribution.py
  numpyro/handlers.py
  numpyro/mcmc.py
  numpyro/util.py
  test/test_distributions.py
  test/test_examples.py
  test/test_mcmc.py
Labels: awaiting review

#181 Minor fix for docs
  docs/source/distributions.rst
  numpyro/util.py
Labels: awaiting review
