Repository pyro-ppl/numpyro, pull requests merged in 2019-10, with the labels that each got.

#374 Minor modifications to numpyro.compat
  numpyro/compat/distributions.py
  numpyro/compat/handlers.py
  numpyro/compat/infer.py
  numpyro/compat/ops.py
Labels: awaiting review

#361 implement auto mvn guide
  docs/source/autoguide.rst
  numpyro/contrib/autoguide/__init__.py
  test/contrib/test_autoguide.py
Labels: awaiting review

#375 Use device utils in examples/tutorials
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/neutra.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/mcmc.py
Labels: awaiting review, easy

#379 Refactor namespace for generic compatibility
  docs/source/conf.py
  docs/source/distributions.rst
  docs/source/mcmc.rst
  docs/source/svi.rst
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/minipyro.py
  examples/neutra.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/__init__.py
  numpyro/compat/distributions.py
  numpyro/compat/infer.py
  numpyro/compat/ops.py
  numpyro/compat/pyro.py
  numpyro/contrib/autoguide/__init__.py
  numpyro/contrib/distributions/distribution.py
  numpyro/diagnostics.py
  numpyro/distributions/__init__.py
  numpyro/distributions/constraints.py
  numpyro/distributions/continuous.py
  numpyro/distributions/distribution.py
  numpyro/distributions/flows.py
  numpyro/distributions/transforms.py
  numpyro/handlers.py
  numpyro/hmc_util.py
  numpyro/infer/__init__.py
  numpyro/infer/mcmc.py
  numpyro/infer/svi.py
  numpyro/infer_util.py
  numpyro/util.py
  test/contrib/test_autoguide.py
  test/test_distributions.py
  test/test_hmc_util.py
  test/test_infer_util.py
  test/test_mcmc.py
  test/test_mcmc_interface.py
  test/test_svi.py
Labels: awaiting review

#382 A pass for 0.2.1 release
  docs/source/mcmc.rst
  docs/source/utilities.rst
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/neutra.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/__init__.py
  numpyro/contrib/autoguide/__init__.py
  numpyro/distributions/__init__.py
  numpyro/handlers.py
  numpyro/infer/__init__.py
  numpyro/infer/hmc_util.py
  numpyro/infer/mcmc.py
  numpyro/infer/svi.py
  numpyro/infer/util.py
  numpyro/util.py
  test/contrib/test_autoguide.py
  test/test_handlers.py
  test/test_hmc_util.py
  test/test_infer_util.py
  test/test_mcmc.py
Labels: awaiting review

#380 add group_by_chain arg to allow summary with flatten samples
  numpyro/diagnostics.py
Labels: awaiting review, easy

#381 Add init_to_value strategy
  docs/source/utilities.rst
  numpyro/contrib/autoguide/__init__.py
  numpyro/infer/hmc_util.py
  numpyro/infer/mcmc.py
  numpyro/infer/util.py
  numpyro/util.py
  test/contrib/test_autoguide.py
  test/test_infer_util.py
Labels: awaiting review

#384 use args kwargs in svi
  examples/minipyro.py
  examples/vae.py
  numpyro/infer/svi.py
  test/contrib/test_autoguide.py
  test/test_svi.py
Labels: awaiting review

#388 Out of support mask
  docs/source/utilities.rst
  numpyro/__init__.py
  numpyro/distributions/continuous.py
  numpyro/distributions/discrete.py
  numpyro/distributions/distribution.py
  numpyro/distributions/util.py
  test/test_distributions.py
Labels: awaiting review

#383 Convert elbo into a class for compatibility with Pyro
  docs/source/autoguide.rst
  docs/source/svi.rst
  examples/minipyro.py
  examples/neutra.py
  examples/vae.py
  numpyro/contrib/autoguide/__init__.py
  numpyro/infer/__init__.py
  numpyro/infer/elbo.py
  numpyro/infer/svi.py
  test/contrib/test_autoguide.py
  test/test_svi.py
Labels: awaiting review

#391 Generic compatibility wrapper for seed handler
  numpyro/compat/handlers.py
Labels: awaiting review, easy

#363 Implement laplace approximation
  docs/source/autoguide.rst
  examples/neutra.py
  numpyro/contrib/autoguide/__init__.py
  numpyro/infer/__init__.py
  numpyro/infer/svi.py
  test/contrib/test_autoguide.py
Labels: awaiting review

#392 swap loss and optim in svi
  examples/minipyro.py
  examples/neutra.py
  examples/vae.py
  numpyro/infer/svi.py
  test/contrib/test_autoguide.py
  test/test_svi.py
Labels: awaiting review, discussion, easy

#390 Add a compat version for SVI, Trace_ELBO.
  numpyro/compat/infer.py
  numpyro/compat/optim.py
Labels: awaiting review

#395 improve turning condition
  numpyro/infer/hmc_util.py
  test/test_hmc_util.py
Labels: awaiting review

#394 fix bug at vectorized method
  numpyro/infer/mcmc.py
  test/test_distributions.py
  test/test_mcmc_interface.py
Labels: awaiting review

#397 Make behavior of nested seed handler consistent with Pyro
  numpyro/handlers.py
  test/test_handlers.py
Labels: awaiting review

#396 Add tests from pyroapi
  numpyro/compat/infer.py
  numpyro/compat/optim.py
  numpyro/compat/pyro.py
  numpyro/compat/util.py
  setup.py
  test/pyroapi/conftest.py
  test/pyroapi/test_pyroapi.py
Labels: awaiting review

#401 More compatibility tweaks for pyro-api
  numpyro/compat/infer.py
  numpyro/compat/ops.py
  numpyro/compat/optim.py
  numpyro/compat/pyro.py
  numpyro/optim.py
  test/pyroapi/test_pyroapi.py
  test/test_optimizers.py
Labels: awaiting review

#399 Defer to autodelta if hessian of laplace approximation is singular
  numpyro/contrib/autoguide/__init__.py
  numpyro/handlers.py
  test/contrib/test_autoguide.py
Labels: awaiting review

#400 fix CategoricalLogits log_prob
  numpyro/distributions/discrete.py
  test/test_distributions.py
Labels: awaiting review

#326 update benchmark notebook
  notebooks/source/logistic_regression.ipynb
Labels: awaiting review

#405 Add BetaBinomial, GammaPoisson, ZeroInflatedPoisson
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/conjugate.py
  numpyro/distributions/discrete.py
  test/test_distributions.py
Labels: awaiting review

#407 Remove test_example marker from tests
  .travis.yml
  test/test_example_utils.py
  test/test_examples.py
Labels: awaiting review

#408 Rename rng argument throughout the codebase
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/compat/handlers.py
  numpyro/compat/infer.py
  numpyro/contrib/autoguide/__init__.py
  numpyro/contrib/distributions/distribution.py
  numpyro/contrib/nn/auto_reg_nn.py
  numpyro/contrib/nn/masked_dense.py
  numpyro/distributions/distribution.py
  numpyro/distributions/util.py
  numpyro/handlers.py
  numpyro/infer/elbo.py
  numpyro/infer/hmc_util.py
  numpyro/infer/mcmc.py
  numpyro/infer/svi.py
  numpyro/infer/util.py
  numpyro/primitives.py
  test/contrib/test_autoguide.py
  test/contrib/test_distributions_contrib.py
  test/contrib/test_nn.py
  test/test_distributions.py
  test/test_distributions_util.py
  test/test_flows.py
  test/test_handlers.py
  test/test_hmc_util.py
  test/test_infer_util.py
  test/test_mcmc.py
  test/test_mcmc_interface.py
  test/test_svi.py
Labels: awaiting review

#403 Implement Low-rank MVN
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/continuous.py
  test/test_distributions.py
Labels: awaiting review

#411 remove depricated svi/mcmc
  .travis.yml
  docs/source/conf.py
  numpyro/infer/mcmc.py
  numpyro/infer/svi.py
  test/test_mcmc.py
  test/test_mcmc_interface.py
Labels: awaiting review

#406 add ordered logistic distribution
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/constraints.py
  numpyro/distributions/discrete.py
  numpyro/distributions/transforms.py
  test/test_distributions.py
Labels: awaiting review

#412 skip numpy warning error for constant values
  numpyro/diagnostics.py
Labels: awaiting review, easy

#409 add parallel arg to predictive
  docs/source/utilities.rst
  examples/baseball.py
  numpyro/infer/__init__.py
  numpyro/infer/util.py
  test/test_infer_util.py
Labels: awaiting review

#425 Minor changes to the time series tutorial
  notebooks/source/time_series_forecasting.ipynb
Labels: awaiting review

#421 Update bayesian regression tutorial
  Makefile
  notebooks/source/_static/css/pyro.css
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/conf.py
  setup.py
Labels: awaiting review
