Repository pyro-ppl/numpyro, pull requests merged in 2019-04, with the labels that each got.

#70 Adding HMC kernel to mcmc
  numpyro/mcmc.py
  numpyro/util.py
  test/test_mcmc.py
Labels: awaiting review

#75 Correct the usage of find reasonable step size function
  numpyro/hmc_util.py
  numpyro/mcmc.py
  setup.cfg
  test/test_hmc_util.py
Labels: awaiting review

#79 Support logits to frozen Bernoulli distribution
  numpyro/distributions/discrete.py
  numpyro/distributions/distribution.py
  numpyro/distributions/util.py
  test/test_distributions.py
  test/test_distributions_util.py
  test/test_mcmc.py
Labels: awaiting review

#81 Implement dirichlet distribution
  numpyro/distributions/__init__.py
  numpyro/distributions/continuous.py
  numpyro/distributions/distribution.py
  numpyro/distributions/multivariate.py
  test/test_distributions.py
Labels: awaiting review

#83 Add nuts update and expose warmup update
  numpyro/hmc_util.py
  numpyro/mcmc.py
  test/test_hmc_util.py
  test/test_mcmc.py
Labels: awaiting review

#86 Add ability to use models directly to do inference in HMC
  numpyro/distributions/multivariate.py
  numpyro/handlers.py
  numpyro/hmc_util.py
  numpyro/mcmc.py
  numpyro/svi.py
  test/test_mcmc.py
Labels: awaiting review

#84 implement a custom lax.scan (for tuple) which only stores selected fields
  numpyro/util.py
  test/test_mcmc.py
  test/test_util.py
Labels: awaiting review

#89 Simplifies scan with prims disabled implementation.
  numpyro/util.py
  test/test_util.py
Labels: awaiting review

#87 Drop recursive NUTS
  numpyro/hmc_util.py
  test/test_hmc_util.py
  test/test_mcmc.py
Labels: awaiting review

#91 Add a transform function to tscan
  numpyro/util.py
  test/test_mcmc.py
  test/test_util.py
Labels: awaiting review, refactor

#93 fix bugs about step size
  numpyro/hmc_util.py
  numpyro/mcmc.py
Labels: awaiting review, easy

#96 Add license for the project
  LICENSE.md
Labels: awaiting review

#95 Add distribution classes that do not depend on scipy
  numpyro/contrib/__init__.py
  numpyro/contrib/distributions/__init__.py
  numpyro/contrib/distributions/continuous.py
  numpyro/contrib/distributions/discrete.py
  numpyro/contrib/distributions/distribution.py
  numpyro/distributions/util.py
  numpyro/util.py
  test/test_distributions_contrib.py
Labels: awaiting review

#94 Add support for constraint
  numpyro/distributions/__init__.py
  numpyro/distributions/constraint_registry.py
  numpyro/distributions/constraints.py
  numpyro/distributions/transforms.py
  test/test_distributions.py
Labels: awaiting review

#98 Add constraints to continuous distribution
  numpyro/distributions/constraint_registry.py
  numpyro/distributions/constraints.py
  numpyro/distributions/continuous.py
  numpyro/distributions/distribution.py
  numpyro/distributions/multivariate.py
  numpyro/distributions/transforms.py
  test/conftest.py
  test/test_distributions.py
Labels: awaiting review, discussion

#99 Unify args validation for discrete and continuous distributions
  numpyro/distributions/constraints.py
  numpyro/distributions/discrete.py
  numpyro/distributions/distribution.py
  numpyro/distributions/util.py
  numpyro/hmc_util.py
  test/conftest.py
  test/test_distributions.py
  test/test_mcmc.py
  test/test_util.py
Labels: awaiting review

#100 Separating out tscan_nonprim to make it easier for benchmarking
  numpyro/util.py
Labels: awaiting review

#104 Update jax/jaxlib versions
  .travis.yml
  setup.py
Labels: awaiting review, easy

#101 Fix various issues of scipy discrete distributions
  numpyro/distributions/__init__.py
  numpyro/distributions/constraints.py
  numpyro/distributions/discrete.py
  numpyro/distributions/distribution.py
  numpyro/distributions/patch.py
  test/conftest.py
  test/test_distributions.py
Labels: awaiting review

#105 Adding more distributions to contrib
  numpyro/contrib/distributions/__init__.py
  numpyro/contrib/distributions/continuous.py
  numpyro/contrib/distributions/discrete.py
  numpyro/contrib/distributions/distribution.py
  numpyro/distributions/constraints.py
  numpyro/distributions/transforms.py
  numpyro/distributions/util.py
  test/test_distributions_contrib.py
Labels: awaiting review

#108 Use transforms for models with constrained latent variables
  numpyro/distributions/transforms.py
  numpyro/handlers.py
  numpyro/hmc_util.py
  numpyro/util.py
  test/test_mcmc.py
Labels: awaiting review

#92 Add benchmark notebook for covtype dataset.
  notebooks/logistic_regression.ipynb
  numpyro/hmc_util.py
Labels: awaiting review

#110 Remove num_steps in favor of trajectory_length in HMC interface
  numpyro/mcmc.py
  test/test_mcmc.py
Labels: awaiting review

#103 add custom transforms cumsum and cumprod
  numpyro/distributions/transforms.py
  numpyro/distributions/util.py
  test/test_distributions.py
  test/test_distributions_util.py
Labels: awaiting review

#111 Add Categorical distribution
  numpyro/distributions/__init__.py
  numpyro/distributions/discrete.py
  numpyro/distributions/distribution.py
  numpyro/distributions/multivariate.py
  numpyro/distributions/util.py
  test/test_distributions.py
  test/test_distributions_util.py
  test/test_mcmc.py
Labels: awaiting review

#115 JIT tscan and HMC warmup steps
  numpyro/__init__.py
  numpyro/examples/covtype.py
  numpyro/mcmc.py
  numpyro/patch.py
  numpyro/util.py
Labels: awaiting review, discussion

#116 Use upstream sampler
  notebooks/logistic_regression.ipynb
  numpyro/distributions/continuous.py
  numpyro/distributions/transforms.py
  numpyro/distributions/util.py
  numpyro/mcmc.py
Labels: awaiting review

#118 Add fori_append construct in util
  numpyro/examples/covtype.py
  numpyro/util.py
  test/test_mcmc.py
  test/test_util.py
Labels: awaiting review, discussion

#120 Use native for loop to collect samples
  numpyro/util.py
  test/test_mcmc.py
  test/test_util.py
Labels: awaiting review

#121 Implement various distributions for benchmarking
  notebooks/logistic_regression.ipynb
  numpyro/distributions/__init__.py
  numpyro/distributions/continuous.py
  numpyro/distributions/discrete.py
  numpyro/distributions/distribution.py
  numpyro/distributions/transforms.py
  test/test_distributions.py
Labels: awaiting review

#124 Add more distributions to contrib
  numpyro/contrib/distributions/__init__.py
  numpyro/contrib/distributions/continuous.py
  numpyro/contrib/distributions/discrete.py
  numpyro/contrib/distributions/distribution.py
  numpyro/distributions/util.py
  test/test_distributions_contrib.py
  test/test_distributions_util.py
Labels: awaiting review

#126 Add CorrCholesky transform
  numpyro/distributions/constraint_registry.py
  numpyro/distributions/constraints.py
  numpyro/distributions/transforms.py
  numpyro/distributions/util.py
  test/test_distributions.py
  test/test_distributions_util.py
Labels: awaiting review

#128 Use contrib.distributions in tests and examples
  numpyro/contrib/distributions/__init__.py
  numpyro/contrib/distributions/continuous.py
  numpyro/contrib/distributions/discrete.py
  numpyro/contrib/distributions/distribution.py
  numpyro/distributions/constraints.py
  numpyro/examples/covtype.py
  numpyro/examples/minipyro.py
  numpyro/handlers.py
  numpyro/hmc_util.py
  numpyro/mcmc.py
  test/test_distributions_contrib.py
Labels: awaiting review

#129 Remove fori_append in favor of fori_collect
  notebooks/logistic_regression.ipynb
  numpyro/examples/covtype.py
  numpyro/mcmc.py
  numpyro/util.py
  test/test_mcmc.py
  test/test_util.py
Labels: awaiting review, easy
