Repository pyro-ppl/numpyro, pull requests merged in 2020-04, with the labels that each got.

#564 use the upstream betaln
  numpyro/distributions/conjugate.py
Labels: awaiting review, easy

#553 Remove find_reasonable_step_size
  numpyro/infer/hmc_util.py
  numpyro/infer/mcmc.py
  test/test_mcmc.py
Labels: awaiting review, discussion, performance

#565 update jax to master 0.1.63
  .travis.yml
  examples/neutra.py
  examples/ode.py
  numpyro/distributions/continuous.py
  numpyro/distributions/transforms.py
  numpyro/distributions/util.py
  setup.py
  test/test_distributions_util.py
Labels: awaiting review

#569 fix bug for models with mask=False
  numpyro/infer/util.py
  numpyro/primitives.py
  test/test_handlers.py
  test/test_infer_util.py
Labels: awaiting review

#573 add enumerate_support method for discrete distributions
  numpyro/distributions/conjugate.py
  numpyro/distributions/discrete.py
  numpyro/distributions/distribution.py
  test/test_distributions.py
Labels: awaiting review

#574 Implement ExpandedDistribution
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/conjugate.py
  numpyro/distributions/discrete.py
  numpyro/distributions/distribution.py
  test/test_distributions.py
Labels: awaiting review

#580 Port pyro.ops.indexing to a new numpyro.contrib.indexing
  docs/source/utilities.rst
  numpyro/contrib/indexing.py
  test/contrib/test_indexing.py
Labels: awaiting review

#581 Adding example for testing proportions
  examples/proportion_test.py
Labels: awaiting review
