Repository pyro-ppl/numpyro, pull requests merged in 2020-11, with the labels that each got.

#795 Reveal signature for help(Distribution)
  numpyro/distributions/distribution.py
Labels: awaiting review

#791 Update documentation page
  .github/workflows/ci.yml
  .gitignore
  docs/Makefile
  docs/requirements.txt
  docs/source/_static/css/pyro.css
  docs/source/_static/img/examples/bnn.png
  docs/source/_static/img/examples/funnel.png
  docs/source/_static/img/examples/gp.png
  docs/source/_static/img/examples/hmm.png
  docs/source/_static/img/examples/neutra.png
  docs/source/_static/img/examples/ode.png
  docs/source/_static/img/examples/stochastic_volatility.png
  docs/source/_static/img/examples/ucbadmit.png
  docs/source/api.rst
  docs/source/conf.py
  docs/source/index.rst
  examples/annotation.py
  examples/baseball.py
  examples/bnn.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/hmm_enum.py
  examples/neutra.py
  examples/ode.py
  examples/proportion_test.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bayesian_hierarchical_linear_regression.ipynb
  notebooks/source/bayesian_imputation.ipynb
  notebooks/source/conf.py
  notebooks/source/discrete_imputation.ipynb
  notebooks/source/index.rst
  setup.py
Labels: awaiting review, discussion

#797 Fix postprocess for MCMC vectorized chain method
  numpyro/infer/mcmc.py
  test/test_mcmc.py
Labels: awaiting review

#805 Fix progbar message when running warmup
  numpyro/infer/mcmc.py
Labels: awaiting review

#806 Update funnel documentation
  examples/funnel.py
Labels: awaiting review

#801 Raise errors early if missing plates for models with discrete latent variable
  numpyro/infer/util.py
  test/contrib/test_funsor.py
Labels: awaiting review

#804 Add prng_key primitive
  docs/source/primitives.rst
  numpyro/__init__.py
  numpyro/compat/infer.py
  numpyro/contrib/module.py
  numpyro/distributions/discrete.py
  numpyro/handlers.py
  numpyro/infer/autoguide.py
  numpyro/infer/elbo.py
  numpyro/infer/util.py
  numpyro/primitives.py
  test/test_handlers.py
Labels: awaiting review

#803 Fix docs build failed while building pdf file
  docs/source/_templates/breadcrumbs.html
  docs/source/conf.py
  examples/stochastic_volatility.py
  notebooks/source/bayesian_hierarchical_linear_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
Labels: awaiting review, documentation

#808 Try to fix colab link
  docs/source/conf.py
  docs/source/funsor.rst
Labels: awaiting review

#811 Relax JAX version
  README.md
  notebooks/source/bayesian_regression.ipynb
  numpyro/handlers.py
  numpyro/infer/util.py
  setup.py
Labels: awaiting review, easy

#799 Simplify training phase of SVI
  examples/neutra.py
  numpyro/contrib/module.py
  numpyro/infer/svi.py
  test/test_svi.py
Labels: awaiting review

#818 Display correct error message and cleanup _PYRO_STACK when error happens
  numpyro/contrib/funsor/infer_util.py
  numpyro/handlers.py
  numpyro/primitives.py
  test/contrib/test_funsor.py
Labels: awaiting review

#817 Add the missing hmm example to docs
  docs/source/index.rst
Labels: awaiting review, easy

#819 Raise a better error message when rng_key is missing
  numpyro/distributions/conjugate.py
  numpyro/distributions/continuous.py
  numpyro/distributions/directional.py
  numpyro/distributions/discrete.py
  numpyro/distributions/util.py
  test/contrib/test_module.py
Labels: awaiting review

#823 demo how to use init strategies in gp.py
  examples/gp.py
Labels: awaiting review, easy

#827 fix test_collapse_beta_binomial
  test/test_handlers.py
Labels: awaiting review, easy, test
