Repository pyro-ppl/numpyro, pull requests merged in 2020-06, with the labels that each got.

#609 Reduce compiling time in MCMC
  examples/hmm.py
  examples/neutra.py
  examples/ode.py
  examples/stochastic_volatility.py
  numpyro/contrib/autoguide/__init__.py
  numpyro/contrib/reparam.py
  numpyro/infer/hmc_util.py
  numpyro/infer/mcmc.py
  numpyro/infer/util.py
  test/contrib/test_autoguide.py
  test/contrib/test_reparam.py
  test/test_compile.py
  test/test_hmc_util.py
  test/test_infer_util.py
  test/test_mcmc.py
Labels: awaiting review

#613 Filter out discrete sites
  numpyro/infer/initialization.py
  numpyro/infer/util.py
Labels: awaiting review

#614 Cleanup autoguide before transfering 1-1 to the main module
  numpyro/contrib/autoguide/__init__.py
  numpyro/contrib/reparam.py
Labels: awaiting review

#617 support Expand Reparam
  numpyro/contrib/autoguide/__init__.py
  numpyro/contrib/reparam.py
  numpyro/distributions/discrete.py
  numpyro/distributions/distribution.py
  numpyro/handlers.py
  numpyro/infer/util.py
  numpyro/primitives.py
  test/contrib/test_reparam.py
Labels: awaiting review

#612 Add Improper Distribution
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/constraints.py
  numpyro/distributions/distribution.py
  numpyro/infer/initialization.py
  numpyro/infer/util.py
  test/test_distributions.py
  test/test_infer_util.py
  test/test_mcmc.py
Labels: awaiting review

#618 Filter out most models with static supports in MCMC
  docs/source/primitives.rst
  numpyro/distributions/continuous.py
  numpyro/infer/mcmc.py
  numpyro/infer/util.py
  numpyro/primitives.py
Labels: awaiting review, easy

#616 Use ExpandedDistribution in numpyro.plate
  numpyro/distributions/distribution.py
  numpyro/primitives.py
Labels: awaiting review, performance

#626 Update jax version to test Travis with latest jax release
  .travis.yml
  examples/hmm.py
  examples/neutra.py
  numpyro/distributions/discrete.py
  numpyro/distributions/transforms.py
  numpyro/distributions/util.py
  numpyro/infer/mcmc.py
  setup.py
  test/test_distributions.py
  test/test_distributions_util.py
Labels: awaiting review, easy

#625 move autoguide the the main module
  docs/source/autoguide.rst
  examples/neutra.py
  numpyro/contrib/autoguide.py
  numpyro/contrib/nn/__init__.py
  numpyro/contrib/reparam.py
  numpyro/infer/autoguide.py
  numpyro/nn/__init__.py
  numpyro/nn/auto_reg_nn.py
  numpyro/nn/block_neural_arn.py
  numpyro/nn/masked_dense.py
  test/contrib/test_reparam.py
  test/test_autoguide.py
  test/test_compile.py
  test/test_distributions.py
  test/test_flows.py
  test/test_nn.py
Labels: awaiting review

#623 von Mises distribution
  numpyro/distributions/__init__.py
  numpyro/distributions/constraints.py
  numpyro/distributions/directional.py
  numpyro/distributions/util.py
  numpyro/infer/util.py
  test/test_distributions.py
Labels: awaiting review

#633 No need for storing jacobian transform if support is real
  numpyro/infer/util.py
Labels: awaiting review, easy

#634 add truncated polya gamma dist to docs
  docs/source/distributions.rst
Labels: awaiting review, documentation, easy

#630 remove seed in likelihood computation in bayesian regression tutorial
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
Labels: awaiting review, easy

#628 Move reparam to the main module
  docs/source/handlers.rst
  docs/source/index.rst
  docs/source/reparam.rst
  examples/funnel.py
  examples/neutra.py
  numpyro/distributions/distribution.py
  numpyro/handlers.py
  numpyro/infer/reparam.py
  test/test_autoguide.py
  test/test_infer_util.py
  test/test_mcmc.py
  test/test_reparam.py
Labels: awaiting review, easy

#635 add logistic to docs
  docs/source/distributions.rst
Labels: awaiting review, documentation, easy

#631 Remove `mask` field in the trace
  numpyro/distributions/util.py
  numpyro/handlers.py
  numpyro/infer/util.py
  numpyro/primitives.py
Labels: awaiting review

#636 Test github action
  .github/workflows/ci.yml
  .travis.yml
  README.md
  docs/source/distributions.rst
  scripts/update_headers.py
  test/test_distributions.py
Labels: awaiting review

#629 update README file to use reparam handler
  .github/workflows/ci.yml
  README.md
Labels: awaiting review

#642 Add scope handler
  docs/source/handlers.rst
  numpyro/handlers.py
  test/test_handlers.py
Labels: awaiting review

#641 Support `hide` argument in block handler
  numpyro/contrib/distributions/distribution.py
  numpyro/handlers.py
  test/test_handlers.py
Labels: awaiting review, easy

#647 Support ImproperUniform in SVI
  numpyro/infer/svi.py
  test/test_autoguide.py
Labels: awaiting review

#648 Fix a bug of init_to_value strategy
  numpyro/compat/ops.py
  numpyro/distributions/discrete.py
  numpyro/infer/autoguide.py
  numpyro/infer/util.py
  test/test_infer_util.py
  test/test_mcmc.py
Labels: awaiting review

#651 Remove contrib.distributions
  .github/workflows/ci.yml
  numpyro/contrib/distributions/__init__.py
  numpyro/contrib/distributions/continuous.py
  numpyro/contrib/distributions/discrete.py
  numpyro/contrib/distributions/distribution.py
  numpyro/contrib/distributions/multivariate.py
  test/contrib/test_distributions_contrib.py
Labels: awaiting review, easy

#652 does not compute logprob of PRNGKey
  numpyro/infer/util.py
Labels: awaiting review, easy
