Repository pyro-ppl/numpyro, pull requests merged in 2020-05, with the labels that each got.

#575 Implement MaskedDistribution
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/discrete.py
  numpyro/distributions/distribution.py
  test/test_distributions.py
Labels: awaiting review

#584 Reduce compiling time in iterative_build_tree
  examples/hmm.py
  examples/neutra.py
  numpyro/distributions/util.py
  numpyro/infer/hmc_util.py
  test/test_hmc_util.py
Labels: awaiting review, jax

#583 Tighter conditions for loops in _poisson sampling
  numpyro/distributions/util.py
Labels: awaiting review

#589 Update jax version
  .travis.yml
  docs/requirements.txt
  setup.py
  test/contrib/test_nn.py
  test/test_flows.py
Labels: awaiting review, easy

#588 add polya-gamma distribution
  numpyro/distributions/__init__.py
  numpyro/distributions/continuous.py
  test/test_distributions.py
Labels: awaiting review

#596 fix numerical issues of Dirichlet distribution
  numpyro/distributions/continuous.py
  numpyro/distributions/discrete.py
Labels: awaiting review

#599 Add reparam handler
  docs/source/primitives.rst
  examples/funnel.py
  examples/neutra.py
  numpyro/__init__.py
  numpyro/contrib/autoguide/__init__.py
  numpyro/contrib/reparam.py
  numpyro/distributions/transforms.py
  numpyro/primitives.py
  test/contrib/test_autoguide.py
  test/contrib/test_reparam.py
  test/test_distributions.py
  test/test_handlers.py
Labels: awaiting review

#607 Add some profiling tests
  .travis.yml
  setup.py
  test/test_compile.py
Labels: awaiting review

#601 Remove base_param_map
  docs/source/autoguide.rst
  docs/source/distributions.rst
  docs/source/utilities.rst
  examples/hmm.py
  examples/neutra.py
  numpyro/contrib/autoguide/__init__.py
  numpyro/contrib/reparam.py
  numpyro/distributions/distribution.py
  numpyro/distributions/transforms.py
  numpyro/handlers.py
  numpyro/infer/__init__.py
  numpyro/infer/hmc_util.py
  numpyro/infer/initialization.py
  numpyro/infer/mcmc.py
  numpyro/infer/util.py
  numpyro/primitives.py
  numpyro/util.py
  test/contrib/test_autoguide.py
  test/contrib/test_reparam.py
  test/test_compile.py
  test/test_hmc_util.py
  test/test_infer_util.py
  test/test_mcmc.py
  test/test_svi.py
Labels: awaiting review

#608 Update the forecasting with the usage of Predictive
  notebooks/source/time_series_forecasting.ipynb
Labels: awaiting review

#605 Switch to use `mask(False)` for improper prior
  numpyro/infer/mcmc.py
  numpyro/infer/util.py
  test/test_infer_util.py
  test/test_mcmc.py
Labels: awaiting review

#606 Refactor initialization strategies
  numpyro/infer/initialization.py
  numpyro/infer/mcmc.py
  numpyro/infer/util.py
  test/test_infer_util.py
  test/test_mcmc.py
Labels: awaiting review
