Repository pyro-ppl/numpyro, pull requests merged in 2020-08, with the labels that each got.

#707 fix rendering issue of hmm_enum example
  examples/hmm_enum.py
Labels: awaiting review, easy

#708 Relax jax version
  docs/source/mcmc.rst
  numpyro/contrib/funsor/infer_util.py
  setup.py
Labels: awaiting review, easy

#709 Implement geometric distribution
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/discrete.py
  test/test_distributions.py
Labels: awaiting review

#638 Add `do` handler
  docs/source/handlers.rst
  numpyro/handlers.py
  test/test_handlers.py
Labels: WIP

#711 Remove future warnings
  numpyro/contrib/autoguide.py
  numpyro/distributions/transforms.py
  numpyro/handlers.py
  numpyro/infer/initialization.py
  numpyro/infer/util.py
Labels: awaiting review, easy

#718 Add tfp distributions
  docs/requirements.txt
  docs/source/distributions.rst
  notebooks/source/conf.py
  numpyro/contrib/control_flow/scan.py
  numpyro/contrib/funsor/enum_messenger.py
  numpyro/contrib/tfp/__init__.py
  numpyro/contrib/tfp/distributions.py
  numpyro/distributions/__init__.py
  numpyro/distributions/continuous.py
  numpyro/distributions/distribution.py
  numpyro/handlers.py
  numpyro/primitives.py
  setup.cfg
  setup.py
  test/contrib/test_module.py
  test/contrib/test_tfp.py
Labels: awaiting review
