Repository pyro-ppl/numpyro, pull requests merged in 2020-12, with the labels that each got.

#831 Expose potential_fn_gen for composed kernels
  numpyro/infer/hmc.py
  numpyro/infer/sa.py
Labels: awaiting review

#821 Fix a bug at MCMC.print_summary
  numpyro/contrib/tfp/distributions.py
  numpyro/distributions/transforms.py
  numpyro/distributions/util.py
  numpyro/handlers.py
  numpyro/infer/mcmc.py
Labels: awaiting review

#832 Allow a callable to return an init value in param primitive
  numpyro/infer/svi.py
  numpyro/primitives.py
  test/test_svi.py
Labels: awaiting review

#828 Kernels module for stein VI
  numpyro/distributions/directional.py
  numpyro/infer/einstein/__init__.py
  numpyro/infer/einstein/kernels.py
  numpyro/infer/einstein/utils.py
  test/test_einstein_kernels.py
Labels: awaiting review

#839 add HMCGibbs sampler
  docs/source/mcmc.rst
  numpyro/infer/__init__.py
  numpyro/infer/hmc_gibbs.py
  test/test_hmc_gibbs.py
Labels: enhancement

#837 Make scan compatible with unconstrain reparam
  docs/source/handlers.rst
  numpyro/contrib/control_flow/scan.py
  numpyro/contrib/funsor/enum_messenger.py
  numpyro/distributions/util.py
  numpyro/handlers.py
  numpyro/infer/util.py
  test/contrib/test_control_flow.py
Labels: awaiting review

#841 add diagnostic string to HMCGibbs
  numpyro/infer/hmc_gibbs.py
Labels: awaiting review, easy

#836 Incorporate input_event_dim/output_event_dim to transforms
  numpyro/contrib/funsor/enum_messenger.py
  numpyro/distributions/distribution.py
  numpyro/distributions/transforms.py
  numpyro/infer/autoguide.py
  numpyro/infer/util.py
  test/test_distributions.py
Labels: awaiting review

#835 Add capture-recapture models
  docs/source/index.rst
  examples/capture_recapture.py
  numpyro/contrib/funsor/infer_util.py
  numpyro/examples/datasets.py
  test/test_examples.py
Labels: awaiting review

#845 Support deterministic sites for HMCGibbs
  numpyro/infer/hmc_gibbs.py
  test/test_hmc_gibbs.py
Labels: awaiting review

#846 Add plots to examples
  docs/source/_static/img/examples/bnn.png
  docs/source/_static/img/examples/funnel.png
  docs/source/_static/img/examples/gp.png
  docs/source/_static/img/examples/hmm.png
  docs/source/_static/img/examples/neutra.png
  docs/source/_static/img/examples/ode.png
  docs/source/_static/img/examples/stochastic_volatility.png
  docs/source/_static/img/examples/ucbadmit.png
  docs/source/_static/img/tutorials/bayesian_hierarchical_linear_regression.png
  docs/source/_static/img/tutorials/bayesian_regression.png
  docs/source/_static/img/tutorials/discrete_imputation.png
  docs/source/_static/img/tutorials/ordinal_regression.png
  docs/source/_static/img/tutorials/time_series_forecasting.png
  examples/bnn.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/neutra.py
  examples/ode.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  test/test_einstein_kernels.py
Labels: awaiting review

#844 Add has_rsample / rsample attribute to distributions
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/continuous.py
  numpyro/distributions/directional.py
  numpyro/distributions/discrete.py
  numpyro/distributions/distribution.py
  numpyro/distributions/kl.py
  test/test_distributions.py
Labels: awaiting review

#849 Expose logits in FooProbs distributions
  numpyro/distributions/discrete.py
Labels: awaiting review

#851 add thinning support to fori_collect
  examples/gp.py
  numpyro/infer/mcmc.py
  numpyro/util.py
  test/test_util.py
Labels: awaiting review

#850 Add discrete and subsample gibbs_fn
  docs/source/mcmc.rst
  notebooks/source/bayesian_hierarchical_linear_regression.ipynb
  numpyro/infer/__init__.py
  numpyro/infer/hmc_gibbs.py
Labels: awaiting review

#848 Support scan markov with history > 1
  docs/source/svi.rst
  examples/hmm_enum.py
  numpyro/contrib/control_flow/scan.py
  numpyro/contrib/funsor/enum_messenger.py
  numpyro/contrib/funsor/infer_util.py
  numpyro/handlers.py
  test/contrib/test_funsor.py
  test/test_examples.py
Labels: awaiting review

#852 Fix bug at support_size and enum of discrete gibbs
  numpyro/infer/hmc_gibbs.py
  test/test_hmc_gibbs.py
Labels: awaiting review

#854 Add various discrete gibbs functions method
  numpyro/infer/hmc_gibbs.py
  test/test_hmc_gibbs.py
Labels: awaiting review
