Repository pyro-ppl/numpyro, pull requests merged in 2020-07, with the labels that each got.

#653 rename param_map to data in handlers
  numpyro/distributions/discrete.py
  numpyro/handlers.py
  numpyro/infer/util.py
  test/test_svi.py
Labels: awaiting review

#654 Match Pyro interface
  docs/source/distributions.rst
  docs/source/utilities.rst
  examples/baseball.py
  examples/proportion_test.py
  notebooks/source/conf.py
  numpyro/compat/pyro.py
  numpyro/contrib/autoguide.py
  numpyro/contrib/control_flow/__init__.py
  numpyro/distributions/__init__.py
  numpyro/distributions/continuous.py
  numpyro/distributions/directional.py
  numpyro/distributions/discrete.py
  numpyro/distributions/distribution.py
  numpyro/distributions/transforms.py
  numpyro/handlers.py
  numpyro/infer/__init__.py
  numpyro/infer/autoguide.py
  numpyro/infer/initialization.py
  numpyro/infer/mcmc.py
  numpyro/primitives.py
  numpyro/util.py
  test/contrib/test_control_flow.py
  test/contrib/test_indexing.py
  test/test_autoguide.py
  test/test_compile.py
  test/test_distributions.py
  test/test_distributions_util.py
  test/test_flows.py
  test/test_handlers.py
  test/test_infer_util.py
  test/test_mcmc.py
  test/test_nn.py
  test/test_reparam.py
Labels: awaiting review

#657 Update forecasting tutorial using scan primitive
  notebooks/source/time_series_forecasting.ipynb
  numpyro/contrib/control_flow/scan.py
Labels: awaiting review

#664 Add Sample Adaptive MCMC algo to baseball example
  examples/baseball.py
  numpyro/infer/mcmc.py
Labels: awaiting review

#662 Split hmc, sa into separate files
  docs/source/conf.py
  docs/source/mcmc.rst
  examples/stochastic_volatility.py
  numpyro/compat/infer.py
  numpyro/infer/__init__.py
  numpyro/infer/hmc.py
  numpyro/infer/mcmc.py
  numpyro/infer/sa.py
  test/test_mcmc.py
Labels: awaiting review, easy

#666 relax condition handler
  numpyro/handlers.py
  test/test_handlers.py
Labels: awaiting review

#660 Add batch_ndims argument in Predictive and log_likelihood
  numpyro/distributions/transforms.py
  numpyro/handlers.py
  numpyro/infer/initialization.py
  numpyro/infer/util.py
  numpyro/util.py
  test/test_infer_util.py
  test/test_util.py
Labels: awaiting review

#667 Add lift handler
  docs/source/handlers.rst
  numpyro/handlers.py
  numpyro/primitives.py
  test/test_handlers.py
Labels: awaiting review

#669 tweak sparse regression example
  examples/sparse_regression.py
Labels: awaiting review, easy

#677 Port LocScaleReparam
  README.md
  docs/source/reparam.rst
  examples/funnel.py
  numpyro/distributions/distribution.py
  numpyro/infer/reparam.py
  test/test_reparam.py
Labels: awaiting review

#670 Add less_than constraint
  docs/source/distributions.rst
  numpyro/distributions/constraints.py
  numpyro/distributions/transforms.py
  test/test_distributions.py
Labels: awaiting review

#676 expose MCMCKernel to docs
  docs/source/mcmc.rst
  numpyro/infer/hmc.py
  numpyro/infer/mcmc.py
Labels: awaiting review

#572 Port funsor-based enumeration machinery for profiling
  .github/workflows/ci.yml
  docs/source/index.rst
  examples/baseball.py
  numpyro/contrib/funsor/__init__.py
  numpyro/contrib/funsor/enum_messenger.py
  numpyro/contrib/funsor/infer_util.py
  numpyro/infer/__init__.py
  numpyro/infer/hmc.py
  numpyro/infer/util.py
  numpyro/primitives.py
  setup.py
  test/contrib/test_funsor.py
  test/test_mcmc.py
Labels: awaiting review

#668 Improve compiling time for the option `find_heuristic_step_size=True`
  numpyro/infer/hmc.py
  numpyro/infer/hmc_util.py
  setup.py
  test/test_compile.py
  test/test_hmc_util.py
Labels: awaiting review, performance

#683 Add default=None to some enum handlers
  numpyro/contrib/funsor/enum_messenger.py
Labels: awaiting review, easy

#680 Add MetropolisHastings algorithm to example of MCMCKernel
  numpyro/infer/mcmc.py
Labels: awaiting review

#684 Promote shape when unflatten expand
  numpyro/distributions/distribution.py
  test/test_distributions.py
Labels: awaiting review

#672 Examples for mixture models
  examples/annotation.py
  numpyro/contrib/funsor/infer_util.py
  numpyro/primitives.py
  test/test_examples.py
Labels: awaiting review

#690 Allow default doc inheritance in sphinx
  docs/requirements.txt
  docs/source/conf.py
  docs/source/funsor.rst
  numpyro/distributions/continuous.py
  numpyro/distributions/directional.py
  numpyro/distributions/discrete.py
  numpyro/distributions/util.py
  numpyro/infer/hmc.py
  numpyro/infer/sa.py
  numpyro/util.py
Labels: awaiting review, documentation, easy

#689 Support MCMC kernel classes to specify sample and default fields
  docs/requirements.txt
  numpyro/infer/hmc.py
  numpyro/infer/mcmc.py
  numpyro/infer/sa.py
Labels: awaiting review, discussion

#693 Rename mask_array to mask to match Pyro api
  numpyro/handlers.py
  test/test_handlers.py
  test/test_infer_util.py
Labels: awaiting review

#692 Move get_diagnostic str to sampler method
  numpyro/infer/hmc.py
  numpyro/infer/mcmc.py
  numpyro/infer/sa.py
Labels: awaiting review

#694 make jit model args work for chains
  numpyro/infer/mcmc.py
  test/test_mcmc.py
Labels: awaiting review

#682 Implement markov(history=1) by scanning discrete latent variables
  examples/hmm_enum.py
  numpyro/contrib/control_flow/scan.py
  numpyro/contrib/funsor/enum_messenger.py
  numpyro/contrib/funsor/infer_util.py
  numpyro/examples/datasets.py
  numpyro/primitives.py
  test/contrib/test_control_flow.py
  test/contrib/test_funsor.py
  test/test_example_utils.py
Labels: awaiting review

#699 Fix masking logic
  numpyro/distributions/distribution.py
  numpyro/handlers.py
  test/test_handlers.py
Labels: awaiting review

#696 fix reshape issue of chain samples
  numpyro/infer/mcmc.py
  test/test_mcmc.py
Labels: awaiting review

#460 Bayesian imputation tutorial
  notebooks/source/bayesian_imputation.ipynb
  notebooks/source/index.rst
Labels: awaiting review

#700 make funsor optional
  numpyro/contrib/control_flow/scan.py
  setup.py
Labels: awaiting review, easy

#697 Bump to version 0.3.0
  README.md
  examples/annotation.py
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/minipyro.py
  examples/neutra.py
  examples/ode.py
  examples/proportion_test.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bayesian_imputation.ipynb
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/conf.py
  notebooks/source/logistic_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/contrib/funsor/__init__.py
  numpyro/version.py
  setup.py
Labels: awaiting review
