Repository pyro-ppl/numpyro, pull requests merged in 2020-09, with the labels that each got.

#720 Adding Bayesian hierarchical linear regression tutorial
  notebooks/source/bayesian_hierarchical_linear_regression.ipynb
  notebooks/source/index.rst
Labels: awaiting review

#728 Fix init_strategy argument not respected in hmc and sa
  notebooks/source/bayesian_imputation.ipynb
  numpyro/infer/hmc.py
  numpyro/infer/sa.py
Labels: awaiting review, bug

#732 Mention about the default platform in README
  README.md
Labels: awaiting review, discussion

#734 Support data subsampling
  docs/source/primitives.rst
  numpyro/__init__.py
  numpyro/contrib/funsor/enum_messenger.py
  numpyro/handlers.py
  numpyro/primitives.py
  setup.py
  test/contrib/test_tfp.py
  test/test_handlers.py
Labels: awaiting review

#740 Avoid `nan` acceptance probability in SA
  numpyro/infer/sa.py
Labels: awaiting review

#747 Add AutoNormal guide
  docs/source/autoguide.rst
  numpyro/distributions/util.py
  numpyro/infer/autoguide.py
  test/test_autoguide.py
Labels: awaiting review, low priority

#733 Validate the model when cannot find valid initial params.
  numpyro/distributions/distribution.py
  numpyro/infer/util.py
Labels: awaiting review

#738 Update ordinal regression tutorial to include proper prior
  notebooks/source/ordinal_regression.ipynb
Labels: awaiting review

#750 Pin jax version to 0.1.77
  .github/workflows/ci.yml
  setup.py
Labels: awaiting review, easy

#721 Add a thin wrapper to use TFP mcmc kernels for NumPyro models
  .github/workflows/ci.yml
  docs/source/distributions.rst
  docs/source/mcmc.rst
  numpyro/contrib/tfp/mcmc.py
  numpyro/infer/hmc.py
  numpyro/infer/sa.py
  test/contrib/test_tfp.py
Labels: awaiting review, discussion

#742 Fix the issue `module` cannot be used with AutoGuide
  numpyro/infer/util.py
  test/test_autoguide.py
Labels: awaiting review

#755 Add pyro branding to docs
  docs/source/_static/css/pyro.css
  docs/source/_static/img/favicon/android-icon-144x144.png
  docs/source/_static/img/favicon/android-icon-192x192.png
  docs/source/_static/img/favicon/android-icon-36x36.png
  docs/source/_static/img/favicon/android-icon-48x48.png
  docs/source/_static/img/favicon/android-icon-72x72.png
  docs/source/_static/img/favicon/android-icon-96x96.png
  docs/source/_static/img/favicon/apple-icon-114x114.png
  docs/source/_static/img/favicon/apple-icon-120x120.png
  docs/source/_static/img/favicon/apple-icon-144x144.png
  docs/source/_static/img/favicon/apple-icon-152x152.png
  docs/source/_static/img/favicon/apple-icon-180x180.png
  docs/source/_static/img/favicon/apple-icon-57x57.png
  docs/source/_static/img/favicon/apple-icon-60x60.png
  docs/source/_static/img/favicon/apple-icon-72x72.png
  docs/source/_static/img/favicon/apple-icon-76x76.png
  docs/source/_static/img/favicon/apple-icon-precomposed.png
  docs/source/_static/img/favicon/apple-icon.png
  docs/source/_static/img/favicon/browserconfig.xml
  docs/source/_static/img/favicon/favicon-16x16.png
  docs/source/_static/img/favicon/favicon-32x32.png
  docs/source/_static/img/favicon/favicon-96x96.png
  docs/source/_static/img/favicon/favicon.ico
  docs/source/_static/img/favicon/manifest.json
  docs/source/_static/img/favicon/ms-icon-144x144.png
  docs/source/_static/img/favicon/ms-icon-150x150.png
  docs/source/_static/img/favicon/ms-icon-310x310.png
  docs/source/_static/img/favicon/ms-icon-70x70.png
  docs/source/_static/img/pyro_logo.png
  docs/source/_static/img/pyro_logo_small.png
  docs/source/_static/img/pyro_logo_wide.png
  docs/source/_static/img/pyro_logo_with_text.png
  docs/source/conf.py
Labels: awaiting review, documentation

#754 Pump jax and tfp-nightly version
  .github/workflows/ci.yml
  examples/annotation.py
  examples/ucbadmit.py
  notebooks/source/bayesian_hierarchical_linear_regression.ipynb
  notebooks/source/bayesian_imputation.ipynb
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/discrete_imputation.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/contrib/tfp/distributions.py
  numpyro/nn/auto_reg_nn.py
  numpyro/nn/block_neural_arn.py
  setup.py
  test/contrib/test_funsor.py
  test/contrib/test_tfp.py
  test/test_distributions.py
  test/test_handlers.py
Labels: awaiting review

#753 Some changes to match Pyro api
  numpyro/distributions/discrete.py
  numpyro/infer/autoguide.py
  numpyro/primitives.py
  test/test_autoguide.py
Labels: awaiting review

#719 Support BFGS minimizer
  docs/source/optimizers.rst
  numpyro/infer/svi.py
  numpyro/optim.py
Labels: awaiting review

#743 Support Flax random module
  .github/workflows/ci.yml
  docs/requirements.txt
  docs/source/primitives.rst
  numpyro/contrib/module.py
  numpyro/contrib/tfp/mcmc.py
  numpyro/infer/util.py
  test/contrib/test_module.py
Labels: awaiting review

#748 Add mean field ELBO
  numpyro/contrib/module.py
  numpyro/distributions/__init__.py
  numpyro/distributions/kl.py
  numpyro/distributions/util.py
  numpyro/infer/__init__.py
  numpyro/infer/elbo.py
  test/test_autoguide.py
  test/test_distributions.py
Labels: awaiting review

#760 Deprecated ELBO in favor of Trace_ELBO
  docs/source/svi.rst
  examples/minipyro.py
  examples/neutra.py
  examples/vae.py
  numpyro/compat/infer.py
  numpyro/infer/__init__.py
  numpyro/infer/autoguide.py
  numpyro/infer/elbo.py
  numpyro/infer/svi.py
  numpyro/optim.py
  test/test_autoguide.py
  test/test_compile.py
  test/test_handlers.py
  test/test_infer_util.py
  test/test_reparam.py
  test/test_svi.py
Labels: awaiting review

#763 Bump to version 0.4.0
  examples/annotation.py
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/minipyro.py
  examples/neutra.py
  examples/ode.py
  examples/proportion_test.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bayesian_imputation.ipynb
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/ordinal_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/version.py
  setup.py
Labels: awaiting review

#764 Use `raise .. from ..` where appropriate
  numpyro/compat/infer.py
  numpyro/contrib/funsor/__init__.py
  numpyro/contrib/module.py
  numpyro/contrib/tfp/__init__.py
  numpyro/distributions/transforms.py
  numpyro/infer/reparam.py
Labels: awaiting review
