Repository pyro-ppl/numpyro, pull requests merged in 2020-01, with the labels that each got.

#509 Implement cholesky 1-rank update/downdate
  numpyro/distributions/util.py
  test/test_distributions_util.py
Labels: awaiting review

#496 Update for jax >= 0.1.55
  docs/requirements.txt
  numpyro/contrib/autoguide/__init__.py
  numpyro/contrib/distributions/discrete.py
  numpyro/contrib/distributions/multivariate.py
  numpyro/distributions/continuous.py
  numpyro/distributions/discrete.py
  numpyro/distributions/util.py
  numpyro/infer/hmc_util.py
  setup.py
  test/test_distributions_util.py
  test/test_svi.py
Labels: awaiting review, jax

#515 Add support for mask handler
  numpyro/handlers.py
  numpyro/infer/util.py
  numpyro/primitives.py
  test/test_handlers.py
Labels: awaiting review

#518 add reference to readme
  README.md
Labels: awaiting review, easy

#517 Fix handler mask trigger GPU platform by default
  numpyro/handlers.py
Labels: awaiting review, easy

#508 implement sample adaptive mcmc
  docs/source/mcmc.rst
  numpyro/distributions/discrete.py
  numpyro/distributions/util.py
  numpyro/infer/__init__.py
  numpyro/infer/hmc_util.py
  numpyro/infer/mcmc.py
  test/test_mcmc.py
Labels: awaiting review

#521 add init scale to some autoguide
  numpyro/contrib/autoguide/__init__.py
  test/contrib/test_autoguide.py
Labels: awaiting review, easy

#504 Add ode example
  examples/ode.py
  numpyro/examples/datasets.py
  test/test_examples.py
Labels: awaiting review

#230 Implement BNAF flow
  numpyro/contrib/nn/__init__.py
  numpyro/contrib/nn/block_neural_arn.py
  numpyro/distributions/flows.py
  numpyro/distributions/util.py
  test/contrib/test_nn.py
  test/test_flows.py
Labels: awaiting review

#522 Add deterministic primitive
  numpyro/__init__.py
  numpyro/handlers.py
  numpyro/infer/elbo.py
  numpyro/infer/util.py
  numpyro/primitives.py
  test/test_handlers.py
  test/test_infer_util.py
  test/test_mcmc.py
Labels: awaiting review

#524 Minor follow up issues with numpyro.deterministic
  numpyro/infer/mcmc.py
  numpyro/infer/util.py
  test/test_mcmc.py
Labels: awaiting review

#525 Fix lynxhare url
  numpyro/examples/datasets.py
Labels: awaiting review, easy

#527 Mention tpu in README
  .travis.yml
  README.md
Labels: awaiting review

#340 Implement AutoBNAFNormal autoguide
  examples/hmm.py
  examples/neutra.py
  notebooks/source/conf.py
  numpyro/contrib/autoguide/__init__.py
  setup.py
  test/contrib/test_autoguide.py
  test/test_examples.py
Labels: awaiting review

#526 Clean up the gallery
  examples/funnel.py
  examples/neutra.py
  examples/ode.py
  examples/vae.py
Labels: awaiting review

#529 add missing docs for some new features
  docs/source/autoguide.rst
  docs/source/distributions.rst
  docs/source/handlers.rst
  docs/source/primitives.rst
  numpyro/distributions/util.py
  numpyro/infer/mcmc.py
  numpyro/primitives.py
  test/test_hmc_util.py
Labels: awaiting review

#530 Bump to version 0.2.4
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/minipyro.py
  examples/neutra.py
  examples/ode.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/version.py
  setup.py
Labels: awaiting review
