Repository pyro-ppl/numpyro, pull requests merged in 2021-07, with the labels that each got.

#1056 ProdLDA example with Haiku + Flax
  docs/source/_static/img/examples/prodlda.png
  docs/source/index.rst
  examples/prodlda.py
  numpyro/distributions/kl.py
  setup.py
  test/test_distributions.py
  test/test_examples.py
Labels: awaiting review

#1086 Support infer_discrete for Predictive
  examples/annotation.py
  numpyro/contrib/funsor/discrete.py
  numpyro/infer/util.py
Labels: awaiting review

#1082 Checklist for 0.7 release
  README.md
  docker/dev/Dockerfile
  docker/release/Dockerfile
  docs/requirements.txt
  docs/source/api.rst
  docs/source/contrib.rst
  docs/source/distributions.rst
  docs/source/index.rst
  docs/source/infer.rst
  docs/source/mcmc.rst
  examples/annotation.py
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gaussian_shells.py
  examples/gp.py
  examples/hmm.py
  examples/minipyro.py
  examples/neutra.py
  examples/ode.py
  examples/prodlda.py
  examples/proportion_test.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/thompson_sampling.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bayesian_hierarchical_linear_regression.ipynb
  notebooks/source/bayesian_imputation.ipynb
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/model_rendering.ipynb
  notebooks/source/ordinal_regression.ipynb
  numpyro/contrib/nested_sampling.py
  numpyro/infer/hmc.py
  numpyro/version.py
  scripts/update_version.py
  setup.py
Labels: awaiting review

#1093 Bump version to 0.7.1
  examples/annotation.py
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gaussian_shells.py
  examples/gp.py
  examples/hmm.py
  examples/minipyro.py
  examples/neutra.py
  examples/ode.py
  examples/prodlda.py
  examples/proportion_test.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/thompson_sampling.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bayesian_hierarchical_linear_regression.ipynb
  notebooks/source/bayesian_imputation.ipynb
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/model_rendering.ipynb
  notebooks/source/ordinal_regression.ipynb
  numpyro/version.py
Labels: awaiting review, high priority

#1084 DOC Add Predictive examples
  numpyro/infer/mcmc.py
  numpyro/infer/svi.py
  numpyro/infer/util.py
Labels: WIP

#1097 Example for Hilbert space approximation of Gaussian processes
  docs/source/_static/img/examples/hsgp.png
  docs/source/index.rst
  examples/hsgp.py
  test/test_examples.py
Labels: awaiting review

#1101 Relax matching device pattern
  numpyro/util.py
Labels: awaiting review, easy, high priority

#1105 Bump to 0.7.2
  examples/annotation.py
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gaussian_shells.py
  examples/gp.py
  examples/hmm.py
  examples/minipyro.py
  examples/neutra.py
  examples/ode.py
  examples/prodlda.py
  examples/proportion_test.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/thompson_sampling.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bayesian_hierarchical_linear_regression.ipynb
  notebooks/source/bayesian_imputation.ipynb
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/model_rendering.ipynb
  notebooks/source/ordinal_regression.ipynb
  numpyro/version.py
Labels: awaiting review

#1080 Circular Reparameterization
  docs/source/distributions.rst
  docs/source/reparam.rst
  numpyro/distributions/constraints.py
  numpyro/distributions/directional.py
  numpyro/infer/reparam.py
  numpyro/infer/util.py
  test/infer/test_reparam.py
Labels: enhancement
