Repository pyro-ppl/numpyro, pull requests merged in 2021-04, with the labels that each got.

#984 Allow setting max tree depth during warmup phase
  numpyro/infer/hmc.py
  numpyro/infer/hmc_util.py
  test/infer/test_mcmc.py
Labels: awaiting review

#986 [breaking change] not setting platform to CPU by default
  README.md
  numpyro/__init__.py
  numpyro/infer/hmc.py
  numpyro/infer/hmc_gibbs.py
  numpyro/infer/mixed_hmc.py
  numpyro/util.py
  setup.py
  test/infer/test_autoguide.py
  test/test_util.py
Labels: awaiting review, discussion

#987 Add pip install for tutorials
  docs/requirements.txt
  notebooks/source/bayesian_hierarchical_linear_regression.ipynb
  notebooks/source/bayesian_imputation.ipynb
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/discrete_imputation.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/model_rendering.ipynb
  notebooks/source/ordinal_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  setup.py
Labels: awaiting review

#1000 Support total_count=0 in multinomial
  numpyro/distributions/util.py
  test/test_distributions_util.py
Labels: awaiting review

#1002 Implement SoftLaplace distribution
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/continuous.py
  test/test_distributions.py
Labels: awaiting review

#1005 Refactor truncated distributions into a separate file
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/continuous.py
  numpyro/distributions/truncated.py
  test/test_distributions.py
Labels: awaiting review, easy

#1003 Implement sparse Poisson.log_prob()
  numpyro/distributions/discrete.py
  test/test_distributions.py
Labels: awaiting review

#998 Add a flag to control regularize mass matrix behavior
  numpyro/handlers.py
  numpyro/infer/barker.py
  numpyro/infer/hmc.py
  numpyro/infer/hmc_util.py
  numpyro/infer/sa.py
  numpyro/infer/util.py
  numpyro/util.py
  test/infer/test_mcmc.py
  test/test_pickle.py
Labels: awaiting review

#1009 Support decorator syntax for handlers
  numpyro/primitives.py
  test/infer/test_reparam.py
Labels: awaiting review, discussion

#1017 Raise error for SVI if model/guide has discrete latent values
  .github/workflows/ci.yml
  numpyro/distributions/conjugate.py
  numpyro/distributions/constraints.py
  numpyro/distributions/discrete.py
  numpyro/distributions/distribution.py
  numpyro/infer/svi.py
  test/infer/test_svi.py
  test/pyroapi/test_pyroapi.py
  test/test_distributions.py
Labels: awaiting review

#1025 Document get_model_relations()
  docs/source/utilities.rst
  numpyro/contrib/einstein/utils.py
  numpyro/contrib/render.py
  numpyro/distributions/directional.py
  numpyro/distributions/util.py
Labels: awaiting review, documentation, easy

#1014 Example: Thompson sampling for Bayesian Optimization with GPs
  docs/source/_static/img/examples/thompson_sampling.png
  docs/source/index.rst
  examples/thompson_sampling.py
Labels: awaiting review

#1027 Fix failing CI due to new black version
  examples/thompson_sampling.py
Labels: awaiting review, easy
