Repository pyro-ppl/numpyro, pull requests merged in 2021-12, with the labels that each got.

#1251 Fix failing tests in jax 0.2.26
  docs/requirements.txt
  numpyro/infer/hmc_util.py
  setup.py
  test/contrib/test_control_flow.py
  test/infer/test_hmc_gibbs.py
  test/test_distributions.py
  test/test_handlers.py
  test/test_model_rendering.py
Labels: awaiting review

#1254 Move contrib.indexing to numpyro.ops
  docs/source/utilities.rst
  examples/annotation.py
  examples/hmm_enum.py
  numpyro/contrib/indexing.py
  numpyro/ops/__init__.py
  numpyro/ops/indexing.py
  test/contrib/test_funsor.py
  test/ops/test_indexing.py
Labels: awaiting review

#1256 Fix CI freezing
  .github/workflows/ci.yml
  test/contrib/einstein/test_einstein_kernels.py
  test/contrib/test_tfp.py
  test/infer/test_hmc_util.py
  test/infer/test_reparam.py
  test/test_distributions.py
  test/test_distributions_util.py
  test/test_util.py
Labels: awaiting review

#1252 Use multipledispatch for kl_registry
  docs/requirements.txt
  numpyro/distributions/kl.py
  setup.cfg
  setup.py
Labels: awaiting review, refactor

#1255 NeuTra - only reparam unobserved sites in the prototype trace
  numpyro/infer/reparam.py
  test/infer/test_reparam.py
Labels: awaiting review

#1245 Add a warning for missing plate statements in the model
  notebooks/source/bad_posterior_geometry.ipynb
  numpyro/infer/autoguide.py
  numpyro/util.py
  test/contrib/test_optim.py
  test/infer/test_autoguide.py
  test/infer/test_svi.py
  test/test_util.py
Labels: awaiting review

#1227 Allow prior to be a callable in random module
  numpyro/contrib/module.py
  test/contrib/test_module.py
Labels: awaiting review

#1259 allow TruncatedNormal to take both low and high
  numpyro/contrib/tfp/distributions.py
  numpyro/distributions/truncated.py
  numpyro/infer/reparam.py
  test/test_distributions.py
Labels: awaiting review

#1258 Extending Predicitive to allow SteinVI
  numpyro/infer/util.py
  test/infer/test_infer_util.py
Labels: discussion
