Repository pyro-ppl/numpyro, pull requests merged in 2021-08, with the labels that each got.

#1110 Fix docstring of scan
  docs/source/index.rst
  numpyro/contrib/control_flow/scan.py
Labels: awaiting review, easy

#1090 Add L1 ball constraint and its corresponding L1BallTransform bijective
  docs/source/distributions.rst
  numpyro/distributions/constraints.py
  numpyro/distributions/transforms.py
  test/test_distributions.py
Labels: awaiting review

#1122 Fix intersphinx links at various places
  numpyro/infer/hmc_gibbs.py
  numpyro/infer/mcmc.py
  numpyro/infer/sa.py
  numpyro/infer/util.py
Labels: awaiting review, easy

#1116 Add format_shapes utility
  docs/source/utilities.rst
  numpyro/util.py
  test/test_util.py
Labels: usability

#1126 smarter warning about discrete inference in SVI models (#1124)
  numpyro/infer/elbo.py
  numpyro/infer/svi.py
  test/infer/test_svi.py
  test/pyroapi/test_pyroapi.py
Labels: warnings & errors

#1063 Porting Sine Bivaraite von Mises from Pyro
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/directional.py
  test/test_distributions.py
Labels: enhancement

#1118 Recommend AutoNormal guide when hessian in AutoLaplace is singular
  numpyro/infer/autoguide.py
Labels: awaiting response

#1123 Add MixtureSameFamily distribution
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/mixtures.py
  test/test_distributions.py
  test/test_distributions_mixture.py
Labels: enhancement

#1138 add base_dist arg to AutoDAIS
  numpyro/infer/autoguide.py
  test/infer/test_autoguide.py
Labels: awaiting review, easy

#1140 Make Sigmoid and StickBreaking transforms more stable
  numpyro/distributions/transforms.py
Labels: awaiting review, easy

#1130 Adding Dirichlet prior for Ordinal Regression case study
  docs/source/distributions.rst
  notebooks/source/ordinal_regression.ipynb
  numpyro/distributions/discrete.py
  numpyro/distributions/transforms.py
  test/test_distributions.py
Labels: WIP
