Repository pyro-ppl/numpyro, pull requests merged in 2021-11, with the labels that each got.

#1087 Example/ssbvm mixture
  docs/source/_static/img/examples/ssbvm_mixture.png
  docs/source/_static/img/examples/ssbvm_mixture_torus_top.png
  docs/source/index.rst
  examples/ssbvm_mixture.py
  numpyro/examples/datasets.py
  test/test_distributions.py
  test/test_examples.py
Labels: Tutorials/Examples

#1204 Make docs build pass
  docs/source/conf.py
  notebooks/source/bayesian_hierarchical_stacking.ipynb
  numpyro/distributions/directional.py
Labels: awaiting review, easy

#1215 Add link to render_model() link in tutorial
  notebooks/source/model_rendering.ipynb
Labels: awaiting review, easy, documentation

#1213 Updated docs for BvM.
  numpyro/distributions/directional.py
Labels: awaiting review, easy

#1218 fix pyro citation in README
  README.md
Labels: awaiting review, easy

#1234 clarify tensorflow_probability.substrates.jax.distributions usage in docs
  docs/source/mcmc.rst
  numpyro/contrib/tfp/distributions.py
Labels: awaiting review, documentation

#1226 Fix autocontinuous not compatible with non-array init values
  numpyro/infer/autoguide.py
  test/infer/test_autoguide.py
Labels: awaiting review, easy
