Repository pyro-ppl/numpyro, pull requests merged in 2021-01, with the labels that each got.

#856 Change prefix P to _PREV_ for scan_enum
  numpyro/contrib/control_flow/scan.py
  numpyro/contrib/funsor/infer_util.py
Labels: awaiting review

#858 Fix discrete_gibbs_fn not compatible with deterministic sites
  numpyro/infer/hmc_gibbs.py
  test/test_hmc_gibbs.py
Labels: awaiting review

#860 Address memory leak of postprocess_fn and lax.map
  numpyro/infer/mcmc.py
Labels: awaiting review

#861 Expose some mcmc states for sequential sampling strategy
  numpyro/distributions/discrete.py
  numpyro/infer/hmc.py
  numpyro/infer/mcmc.py
  test/test_mcmc.py
Labels: awaiting review, discussion

#866 Add note on how to convert num_steps to tree_depth
  numpyro/infer/hmc.py
Labels: awaiting review, documentation

#867 Fix a typo in regression notebook
  notebooks/source/bayesian_regression.ipynb
  numpyro/__init__.py
  numpyro/contrib/funsor/enum_messenger.py
  numpyro/distributions/__init__.py
  numpyro/distributions/kl.py
  numpyro/examples/datasets.py
  numpyro/infer/autoguide.py
  numpyro/infer/einstein/kernels.py
  numpyro/infer/hmc_gibbs.py
  numpyro/infer/svi.py
  test/test_autoguide.py
  test/test_distributions.py
  test/test_einstein_kernels.py
  test/test_hmc_gibbs.py
  test/test_svi.py
Labels: awaiting review

#868 Warn instead of raising ValueError when substituting a different size subsample indices
  numpyro/primitives.py
Labels: awaiting review

#872 Add default values to constraints to make grad propogate properly
  numpyro/distributions/constraints.py
  numpyro/distributions/distribution.py
  test/test_distributions.py
Labels: awaiting review

#875 Add _InverseTransform
  numpyro/contrib/tfp/distributions.py
  numpyro/distributions/transforms.py
  test/test_distributions.py
Labels: awaiting review

#873 Revise API of gibbs functions
  docs/source/mcmc.rst
  examples/capture_recapture.py
  examples/gp.py
  numpyro/infer/__init__.py
  numpyro/infer/hmc_gibbs.py
  setup.py
  test/test_hmc_gibbs.py
Labels: awaiting review

#876 Add constraint event_dim
  numpyro/contrib/tfp/distributions.py
  numpyro/distributions/constraints.py
  numpyro/distributions/continuous.py
  numpyro/distributions/distribution.py
  numpyro/distributions/flows.py
  numpyro/distributions/transforms.py
  numpyro/infer/autoguide.py
  numpyro/infer/initialization.py
  numpyro/infer/util.py
  test/test_distributions.py
Labels: awaiting review

#865 Make subsample faster in CPU
  numpyro/primitives.py
  test/test_handlers.py
Labels: awaiting review

#882 Relax jax jaxlib versions
  examples/ode.py
  examples/proportion_test.py
  numpyro/contrib/tfp/__init__.py
  numpyro/distributions/directional.py
  numpyro/distributions/util.py
  numpyro/infer/einstein/kernels.py
  numpyro/infer/einstein/utils.py
  numpyro/infer/hmc.py
  numpyro/infer/hmc_gibbs.py
  numpyro/infer/mcmc.py
  numpyro/infer/sa.py
  setup.py
  test/test_einstein_kernels.py
Labels: awaiting review

#883 Improve kinetic energy gradient computation for eucleadian kinetic energy
  numpyro/infer/hmc_util.py
Labels: awaiting review

#878 Support forward-mode differentiation
  numpyro/infer/hmc.py
  numpyro/infer/hmc_util.py
  numpyro/infer/util.py
  test/test_mcmc.py
Labels: awaiting review

#880 Move einstein to contrib
  numpyro/contrib/einstein/__init__.py
  numpyro/contrib/einstein/kernels.py
  numpyro/contrib/einstein/utils.py
  test/contrib/einstein/test_einstein_kernels.py
Labels: awaiting review, easy

#885 Memoize Transform.inv
  numpyro/distributions/transforms.py
  test/test_distributions.py
Labels: awaiting review, easy

#887 Add transforms' forward_shape and inverse_shape
  numpyro/contrib/tfp/distributions.py
  numpyro/distributions/constraints.py
  numpyro/distributions/distribution.py
  numpyro/distributions/flows.py
  numpyro/distributions/transforms.py
  numpyro/infer/initialization.py
  test/test_distributions.py
Labels: awaiting review

#886 Make TransformReparam compatible with .to_event()
  numpyro/infer/reparam.py
  test/test_reparam.py
Labels: awaiting review, bug

#884 Enhance DiscreteHMCGibbs and HMCECS
  numpyro/contrib/funsor/enum_messenger.py
  numpyro/infer/hmc_gibbs.py
  test/test_hmc_gibbs.py
Labels: awaiting review

#888 Bump to version 0.5.0
  examples/annotation.py
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/minipyro.py
  examples/neutra.py
  examples/ode.py
  examples/proportion_test.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bayesian_imputation.ipynb
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/ordinal_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/contrib/einstein/kernels.py
  numpyro/infer/hmc_gibbs.py
  numpyro/infer/hmc_util.py
  numpyro/infer/reparam.py
  numpyro/version.py
  setup.py
Labels: awaiting review

#893 Move the warning of using the sequential chain method to the constructor
  numpyro/infer/mcmc.py
Labels: awaiting review
