Repository pyro-ppl/numpyro, pull requests merged in 2021-05, with the labels that each got.

#1007 Add ZeroInflatedDistribution
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/discrete.py
  test/test_distributions.py
Labels: awaiting review

#1028 Add `cond` primitive
  docs/source/primitives.rst
  numpyro/contrib/control_flow/__init__.py
  numpyro/contrib/control_flow/cond.py
  numpyro/contrib/control_flow/scan.py
  numpyro/contrib/control_flow/util.py
  test/contrib/test_control_flow.py
Labels: awaiting review

#784 Adding conda install instructions
  README.md
Labels: blocked, discussion

#1039 More distributions
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/conjugate.py
  numpyro/distributions/continuous.py
  test/test_distributions.py
Labels: enhancement

#1040 explicit num_warmup, num_samples arguments for MCMC
  examples/annotation.py
  examples/baseball.py
  examples/bnn.py
  examples/capture_recapture.py
  examples/covtype.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/hmm_enum.py
  examples/neutra.py
  examples/ode.py
  examples/proportion_test.py
  examples/sparse_regression.py
  examples/ucbadmit.py
  notebooks/source/bayesian_hierarchical_linear_regression.ipynb
  notebooks/source/bayesian_imputation.ipynb
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/discrete_imputation.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/model_rendering.ipynb
  notebooks/source/ordinal_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/compat/infer.py
  numpyro/handlers.py
  numpyro/infer/hmc_gibbs.py
  numpyro/infer/mcmc.py
  numpyro/infer/mixed_hmc.py
  test/contrib/test_control_flow.py
  test/contrib/test_infer_discrete.py
  test/contrib/test_module.py
  test/contrib/test_tfp.py
  test/infer/test_hmc_gibbs.py
  test/infer/test_mcmc.py
  test/test_compile.py
  test/test_pickle.py
Labels: awaiting review

#1042 Add some png thumnail images for examples/tutorials
  docs/source/_static/img/examples/annotation.png
  docs/source/_static/img/examples/baseball.png
  docs/source/_static/img/examples/capture_recapture.png
  docs/source/_static/img/examples/covtype.png
  docs/source/_static/img/examples/hmm_enum.png
  docs/source/_static/img/examples/proportion_test.png
  docs/source/_static/img/examples/sparse_regression.png
  docs/source/_static/img/examples/vae.png
  docs/source/_static/img/tutorials/bayesian_imputation.png
  docs/source/_static/img/tutorials/model_rendering.png
Labels: awaiting review, easy

#1041 Bump nbsphinx version
  docs/requirements.txt
  setup.py
Labels: awaiting review, easy
