Repository pyro-ppl/numpyro, pull requests merged in 2021-02, with the labels that each got.

#901 Add Distribution.infer_shapes() for static shape analysis
  Makefile
  numpyro/distributions/conjugate.py
  numpyro/distributions/constraints.py
  numpyro/distributions/continuous.py
  numpyro/distributions/discrete.py
  numpyro/distributions/distribution.py
  test/test_distributions.py
Labels: awaiting review

#913 Add positive ordered vector constraint, deprecate InvCholeskyTransform
  docs/source/distributions.rst
  numpyro/distributions/constraints.py
  numpyro/distributions/continuous.py
  numpyro/distributions/transforms.py
  test/test_distributions.py
Labels: awaiting review

#904 Mention that progress_bar=False can require more memory than progress_bar=True
  numpyro/infer/mcmc.py
Labels: awaiting review, easy

#912 Fix svi.run with small num_steps
  numpyro/infer/svi.py
  test/test_svi.py
Labels: awaiting review, easy

#916 Add goodness of fit helpers for testing distributions
  Makefile
  numpyro/distributions/gof.py
  numpyro/handlers.py
  scripts/update_headers.py
  setup.cfg
  setup.py
  test/test_distributions.py
  test/test_hmc_gibbs.py
Labels: awaiting review, test

#908 Fix DiscreteHMCGibbs to work with multiple chains
  .github/workflows/ci.yml
  numpyro/infer/hmc_gibbs.py
  numpyro/infer/hmc_util.py
  test/test_hmc_gibbs.py
  test/test_hmc_util.py
Labels: awaiting review

#915 Add one-sided/two-sided truncated distribution and cdf/icdf method for univariate symmetric distributions
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/continuous.py
  numpyro/distributions/distribution.py
  test/test_distributions.py
Labels: awaiting review, low priority

#910 Add constraints.sphere, dist.ProjectedNormal, ProjectedNormalReparam
  docs/source/distributions.rst
  docs/source/reparam.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/constraints.py
  numpyro/distributions/directional.py
  numpyro/distributions/util.py
  numpyro/infer/reparam.py
  test/test_distributions.py
  test/test_distributions_util.py
  test/test_reparam.py
Labels: awaiting review, enhancement

#921 Reduce memory requirement for AutoLowRankMultivariateNormal.quantiles
  numpyro/infer/autoguide.py
Labels: awaiting review

#922 add BarkerMH kernel
  .github/workflows/ci.yml
  docs/source/mcmc.rst
  numpyro/infer/__init__.py
  numpyro/infer/barker.py
  numpyro/infer/hmc_util.py
  test/contrib/test_tfp.py
  test/infer/test_autoguide.py
  test/infer/test_hmc_gibbs.py
  test/infer/test_hmc_util.py
  test/infer/test_infer_util.py
  test/infer/test_mcmc.py
  test/infer/test_reparam.py
  test/infer/test_svi.py
Labels: awaiting review

#924 Improving compiling time in MCMC samplers
  numpyro/infer/barker.py
  numpyro/infer/hmc.py
  numpyro/infer/sa.py
Labels: awaiting review

#925 add dense_mass=True support to BarkerMH
  numpyro/infer/barker.py
  test/infer/test_mcmc.py
Labels: WIP

#926 Store mass_sqrt_inv in adapt state
  .github/workflows/ci.yml
  numpyro/infer/barker.py
  numpyro/infer/hmc_util.py
  test/infer/test_hmc_util.py
  test/test_examples.py
Labels: awaiting review

#919 adding Softplus transform
  docs/source/distributions.rst
  numpyro/distributions/transforms.py
  test/test_distributions.py
Labels: awaiting response, enhancement

#934 Fix student-t.cdf numerical issue
  numpyro/distributions/continuous.py
Labels: awaiting review
