Repository pyro-ppl/numpyro, pull requests merged in 2021-09, with the labels that each got.

#1145 fix bnaf docstring
  numpyro/infer/autoguide.py
Labels: awaiting review, easy, documentation

#1141 add basic horseshoe regression example
  docs/source/index.rst
  examples/horseshoe_regression.py
  test/test_examples.py
Labels: awaiting review, easy

#1147 Support autoguide subsample with deterministic sites
  numpyro/infer/autoguide.py
  test/infer/test_autoguide.py
Labels: awaiting review

#1142 add notebook that explores bad posterior geometries and tips for dealing with them
  docs/source/index.rst
  notebooks/source/bad_posterior_geometry.ipynb
Labels: awaiting review, documentation

#1148 fix prior in horsehoe example
  examples/horseshoe_regression.py
Labels: awaiting review, easy

#1146 add ScaledUnitLowerCholeskyTransform and change default AutoMultivariateNormal parameterization
  docs/source/distributions.rst
  numpyro/distributions/constraints.py
  numpyro/distributions/transforms.py
  numpyro/infer/autoguide.py
  test/test_distributions.py
Labels: enhancement, awaiting review, discussion

#1149 raise value error if num_steps bad in svi.run
  numpyro/infer/svi.py
Labels: awaiting review, easy

#1153 tweak autodais initialization and parameterization
  numpyro/infer/autoguide.py
Labels: awaiting review, easy

#1152 add plate to bnn.py example for clarity
  examples/bnn.py
Labels: awaiting review, easy

#1055 Sine Skewed distribution
  docs/source/distributions.rst
  numpyro/compat/pyro.py
  numpyro/distributions/__init__.py
  numpyro/distributions/directional.py
  test/test_distributions.py
Labels: enhancement, awaiting review

#1157 Fix import issue for the last jax release
  numpyro/handlers.py
  numpyro/infer/hmc.py
  numpyro/infer/mcmc.py
  test/contrib/test_optim.py
  test/infer/test_compute_downstream_costs.py
  test/test_optimizers.py
Labels: awaiting review, easy

#1166 Fix sphinx sidebar
  docs/source/distributions.rst
  notebooks/source/bad_posterior_geometry.ipynb
  notebooks/source/ordinal_regression.ipynb
Labels: awaiting review, easy

#1058 Add warning when initializing a substituted model
  numpyro/handlers.py
  numpyro/infer/initialization.py
  test/infer/test_mcmc.py
Labels: awaiting review
