Repository pyro-ppl/numpyro, pull requests merged in 2021-03, with the labels that each got.

#941 Use softplus transform in autoguide
  docs/source/distributions.rst
  numpyro/distributions/constraints.py
  numpyro/distributions/transforms.py
  numpyro/infer/autoguide.py
  test/infer/test_autoguide.py
  test/test_distributions.py
Labels: awaiting review

#946 Fix AutoDelta with deterministic sites
  docs/source/distributions.rst
  examples/neutra.py
  numpyro/infer/autoguide.py
  test/infer/test_autoguide.py
  test/pyroapi/test_pyroapi.py
Labels: awaiting review

#943 Improve precision for dirchlet sampler
  numpyro/distributions/continuous.py
  test/infer/test_infer_util.py
  test/infer/test_svi.py
  test/test_distributions.py
Labels: awaiting review

#938 Support obs_mask in sample statement.
  numpyro/primitives.py
  test/test_handlers.py
Labels: awaiting review

#947 Port get_mask to NumPyro
  docs/source/primitives.rst
  numpyro/__init__.py
  numpyro/handlers.py
  numpyro/infer/autoguide.py
  numpyro/infer/hmc_gibbs.py
  numpyro/infer/reparam.py
  numpyro/infer/util.py
  numpyro/primitives.py
  test/infer/test_infer_util.py
Labels: awaiting review

#900 Pbar jitted mcmc
  numpyro/infer/mcmc.py
  numpyro/util.py
  test/infer/test_reparam.py
Labels: awaiting review

#959 Bump to 0.6.0
  README.md
  docs/source/distributions.rst
  docs/source/mcmc.rst
  examples/annotation.py
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gp.py
  examples/hmm.py
  examples/minipyro.py
  examples/neutra.py
  examples/ode.py
  examples/proportion_test.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/ordinal_regression.ipynb
  numpyro/__init__.py
  numpyro/contrib/tfp/distributions.py
  numpyro/distributions/discrete.py
  numpyro/distributions/transforms.py
  numpyro/distributions/util.py
  numpyro/infer/__init__.py
  numpyro/infer/barker.py
  numpyro/infer/hmc.py
  numpyro/infer/hmc_gibbs.py
  numpyro/infer/hmc_util.py
  numpyro/infer/mcmc.py
  numpyro/infer/mixed_hmc.py
  numpyro/infer/sa.py
  numpyro/infer/svi.py
  numpyro/util.py
  numpyro/version.py
  scripts/update_version.py
  setup.py
  test/contrib/test_tfp.py
  test/test_util.py
Labels: awaiting review

#963 Support structural mass matrix in HMC
  numpyro/infer/barker.py
  numpyro/infer/hmc.py
  numpyro/infer/hmc_util.py
  numpyro/infer/util.py
  test/infer/test_hmc_gibbs.py
  test/infer/test_infer_util.py
  test/infer/test_mcmc.py
  test/test_handlers.py
Labels: awaiting review

#966 Update docs for structured mass matrix in hmc
  numpyro/infer/hmc.py
Labels: awaiting review, easy

#968 Support pickling MCMC objects
  numpyro/infer/hmc.py
  numpyro/infer/hmc_gibbs.py
  numpyro/infer/mcmc.py
  numpyro/infer/mixed_hmc.py
  numpyro/infer/sa.py
  test/test_handlers.py
  test/test_pickle.py
Labels: awaiting review

#952 Automatic rendering of probabilistic graphical models
  .github/workflows/ci.yml
  docs/source/index.rst
  docs/source/utilities.rst
  notebooks/source/index.rst
  notebooks/source/model_rendering.ipynb
  numpyro/__init__.py
  numpyro/contrib/render.py
  setup.py
  test/test_model_rendering.py
Labels: awaiting review

#972 Fix a regression bug for `ExpandedDistribution`
  numpyro/distributions/distribution.py
  test/test_distributions.py
Labels: awaiting review, bug

#975 Raise errors on CI for doctest
  .github/workflows/ci.yml
  docs/Makefile
  docs/requirements.txt
  docs/source/utilities.rst
  examples/stochastic_volatility.py
  notebooks/source/bayesian_hierarchical_linear_regression.ipynb
  notebooks/source/bayesian_imputation.ipynb
  notebooks/source/model_rendering.ipynb
  numpyro/contrib/render.py
  numpyro/distributions/continuous.py
  numpyro/distributions/discrete.py
  numpyro/distributions/transforms.py
  numpyro/distributions/util.py
  numpyro/examples/datasets.py
  numpyro/handlers.py
  numpyro/infer/hmc.py
  numpyro/infer/svi.py
  numpyro/primitives.py
  setup.py
Labels: awaiting review
