Repository pyro-ppl/numpyro, pull requests merged in 2022-04, with the labels that each got.

#1381 Added `render_params` argument in `render_model`
  notebooks/source/model_rendering.ipynb
  numpyro/contrib/render.py
  numpyro/ops/provenance.py
  numpyro/ops/pytree.py
Labels: awaiting review

#1386 Update for JAX 0.3.5
  examples/baseball.py
  numpyro/contrib/control_flow/scan.py
  numpyro/contrib/einstein/steinvi.py
  numpyro/contrib/einstein/util.py
  numpyro/distributions/continuous.py
  numpyro/infer/hmc_util.py
  numpyro/infer/mcmc.py
  test/contrib/einstein/test_einstein_util.py
  test/contrib/test_nested_sampling.py
  test/infer/test_infer_util.py
  test/test_distributions.py
  test/test_handlers.py
  test/test_optimizers.py
  test/test_util.py
Labels: awaiting review, high priority

#1387 Clamp probs in BinomialProbs
  numpyro/distributions/discrete.py
Labels: awaiting review, easy

#1389 Fix sphinx distribution docs signature
  numpyro/distributions/distribution.py
Labels: awaiting review

#1388 Update jaxns to 1.0.0
  docs/requirements.txt
  examples/gaussian_shells.py
  numpyro/contrib/nested_sampling.py
  setup.py
  test/contrib/test_nested_sampling.py
Labels: awaiting review

#1338 Do not rename plates under scope handler
  numpyro/contrib/control_flow/scan.py
  numpyro/handlers.py
  test/test_handlers.py
Labels: awaiting review

#1384 Enhance LocScaleReparam noncenter dependency
  numpyro/infer/reparam.py
  test/infer/test_reparam.py
Labels: awaiting review

#1391 Bump to 0.9.2
  examples/annotation.py
  examples/ar2.py
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gaussian_shells.py
  examples/gp.py
  examples/hmm.py
  examples/holt_winters.py
  examples/horseshoe_regression.py
  examples/minipyro.py
  examples/mortality.py
  examples/neutra.py
  examples/ode.py
  examples/prodlda.py
  examples/proportion_test.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/thompson_sampling.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bad_posterior_geometry.ipynb
  notebooks/source/bayesian_hierarchical_linear_regression.ipynb
  notebooks/source/bayesian_hierarchical_stacking.ipynb
  notebooks/source/bayesian_imputation.ipynb
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/model_rendering.ipynb
  notebooks/source/ordinal_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/version.py
Labels: awaiting review, easy
