Repository pyro-ppl/numpyro, pull requests merged in 2022-02, with the labels that each got.

#1314 Stein VI docs
  docs/source/contrib.rst
  numpyro/contrib/einstein/kernels.py
  numpyro/contrib/einstein/steinvi.py
  setup.py
Labels: awaiting review

#1320 Fix provenance logic for jax 0.2.28
  numpyro/ops/provenance.py
  setup.py
Labels: awaiting review

#1326 Raise error for using both posterior samples and guide in Predictive
  numpyro/infer/util.py
Labels: awaiting review, easy

#1325 Fix compat MCMC signature
  numpyro/compat/infer.py
Labels: awaiting review

#1337 Cleanup future warnings
  docs/source/distributions.rst
  numpyro/contrib/indexing.py
  numpyro/distributions/__init__.py
  numpyro/distributions/discrete.py
  numpyro/distributions/transforms.py
  numpyro/handlers.py
  numpyro/infer/autoguide.py
  numpyro/infer/hmc_gibbs.py
Labels: awaiting review, easy

#1344 Fixed url in stein dmm example docs
  examples/stein_dmm.py
Labels: awaiting review, easy

#1332 AsymmetricLaplace distributions
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/continuous.py
  test/test_distributions.py
Labels: WIP

#1345 Make replay consistent with Pyro
  numpyro/distributions/distribution.py
  numpyro/handlers.py
  numpyro/primitives.py
  test/test_distributions.py
Labels: awaiting review

#1349 Bump to version 0.9.1
  examples/annotation.py
  examples/ar2.py
  examples/baseball.py
  examples/bnn.py
  examples/covtype.py
  examples/funnel.py
  examples/gaussian_shells.py
  examples/gp.py
  examples/hmm.py
  examples/holt_winters.py
  examples/horseshoe_regression.py
  examples/minipyro.py
  examples/neutra.py
  examples/ode.py
  examples/prodlda.py
  examples/proportion_test.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/thompson_sampling.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bad_posterior_geometry.ipynb
  notebooks/source/bayesian_hierarchical_linear_regression.ipynb
  notebooks/source/bayesian_hierarchical_stacking.ipynb
  notebooks/source/bayesian_imputation.ipynb
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/model_rendering.ipynb
  notebooks/source/ordinal_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/version.py
Labels: awaiting review, easy
