Repository pyro-ppl/numpyro, pull requests merged in 2022-06, with the labels that each got.

#1418 Fix parallel chain for SA kernel
  numpyro/infer/util.py
  test/infer/test_mcmc.py
Labels: awaiting review

#1426 add AutoSemiDAIS
  README.md
  docs/source/autoguide.rst
  numpyro/distributions/distribution.py
  numpyro/infer/autoguide.py
  numpyro/infer/util.py
  test/infer/test_autoguide.py
  test/infer/test_reparam.py
Labels: enhancement, awaiting review

#1436 set self._postprocess_fn = None in BarkerMH
  numpyro/infer/barker.py
  test/infer/test_mcmc.py
Labels: awaiting review, easy

#1434 add AutoSurrogateLikelihoodDAIS
  README.md
  docs/source/autoguide.rst
  numpyro/handlers.py
  numpyro/infer/autoguide.py
  test/infer/test_autoguide.py
Labels: enhancement, awaiting review

#1441 More stable check for corr_cholesky
  numpyro/distributions/constraints.py
Labels: awaiting review

#1444 Promote shapes of scanned values
  numpyro/contrib/control_flow/scan.py
  test/contrib/test_control_flow.py
Labels: awaiting review
