Repository pyro-ppl/numpyro, pull requests merged in 2022-01, with the labels that each got.

#1269 Add a warning for calling inverse of a non-bijective transform
  numpyro/distributions/transforms.py
  numpyro/infer/reparam.py
  numpyro/util.py
Labels: awaiting review

#1270 Support kl divergence for TFP distributions
  numpyro/contrib/tfp/distributions.py
  setup.cfg
  test/contrib/test_tfp.py
Labels: awaiting review

#1273 Add a note to annotation examples on how to use the mcmc class with arviz
  README.md
  examples/annotation.py
Labels: awaiting review

#1275 Update fori_collect for new ravel_pytree behavior
  numpyro/distributions/continuous.py
  numpyro/util.py
Labels: awaiting review

#1263 Initializing batch of parameters for SteinVI
  numpyro/contrib/einstein/kernels.py
  numpyro/contrib/einstein/util.py
  numpyro/distributions/constraints.py
  numpyro/distributions/directional.py
  test/contrib/einstein/test_batch_params.py
Labels: discussion

#1288 Add Other Inference Algorithms section to docs
  docs/source/index.rst
Labels: easy

#1289 Make hmc gibs algorithms work with improper distributions
  numpyro/infer/hmc_gibbs.py
  test/infer/test_hmc_gibbs.py
Labels: awaiting review

#1277 Feature/batch ravel pytree
  numpyro/contrib/einstein/util.py
  test/contrib/einstein/test_einstein_util.py
Labels: awaiting review, discussion

#1290 Expose potential_fn_gen in autoguide
  numpyro/infer/autoguide.py
Labels: awaiting review

#1272 Tutorial for truncated distributions
  docs/source/index.rst
  notebooks/source/index.rst
  notebooks/source/truncated_distributions.ipynb
Labels: awaiting review

#1302 Make potential_fn_gen and postprocess_fn_gen picklable
  numpyro/infer/autoguide.py
  numpyro/infer/barker.py
  numpyro/infer/hmc.py
  numpyro/infer/sa.py
  numpyro/infer/util.py
Labels: awaiting review

#1303 Improve error messages when missing rng_key for subsampling
  numpyro/infer/autoguide.py
  numpyro/primitives.py
Labels: awaiting review, easy

#1248 Add ProvenanceArray to infer relational structure in a model
  docs/source/utilities.rst
  notebooks/source/model_rendering.ipynb
  numpyro/__init__.py
  numpyro/contrib/control_flow/cond.py
  numpyro/contrib/control_flow/scan.py
  numpyro/contrib/render.py
  numpyro/infer/inspect.py
  numpyro/ops/provenance.py
  numpyro/ops/pytree.py
  test/infer/test_inspect.py
  test/ops/test_provenance.py
Labels: awaiting review

#1305 Fix HMCECS for likelihoods with multiple plates
  numpyro/infer/hmc_gibbs.py
  test/infer/test_hmc_gibbs.py
Labels: awaiting response

#1283 Add Kumaraswamy and relaxed Bernoulli distributions
  docs/source/distributions.rst
  numpyro/distributions/__init__.py
  numpyro/distributions/continuous.py
  numpyro/distributions/distribution.py
  test/test_distributions.py
Labels: awaiting response

#1284 Add various KL divergences for Gamma/Beta families
  numpyro/distributions/continuous.py
  numpyro/distributions/kl.py
  test/test_distributions.py
Labels: awaiting review

#1304 Add loose strategy for missing plates in MCMC
  .github/workflows/ci.yml
  examples/prodlda.py
  examples/vae.py
  numpyro/contrib/tfp/distributions.py
  numpyro/infer/elbo.py
  numpyro/infer/inspect.py
  numpyro/infer/util.py
  numpyro/util.py
  test/contrib/test_funsor.py
  test/infer/test_autoguide.py
  test/infer/test_hmc_gibbs.py
  test/infer/test_infer_util.py
  test/infer/test_mcmc.py
  test/test_distributions.py
  test/test_examples.py
  test/test_util.py
Labels: awaiting review

#1310 Bump to 0.9.0
  .github/workflows/ci.yml
  docs/source/optimizers.rst
  examples/annotation.py
  examples/ar2.py
  examples/baseball.py
  examples/bnn.py
  examples/capture_recapture.py
  examples/covtype.py
  examples/funnel.py
  examples/gaussian_shells.py
  examples/gp.py
  examples/hmm.py
  examples/hmm_enum.py
  examples/holt_winters.py
  examples/horseshoe_regression.py
  examples/hsgp.py
  examples/minipyro.py
  examples/neutra.py
  examples/ode.py
  examples/prodlda.py
  examples/proportion_test.py
  examples/sparse_regression.py
  examples/stochastic_volatility.py
  examples/thompson_sampling.py
  examples/ucbadmit.py
  examples/vae.py
  notebooks/source/bad_posterior_geometry.ipynb
  notebooks/source/bayesian_hierarchical_linear_regression.ipynb
  notebooks/source/bayesian_hierarchical_stacking.ipynb
  notebooks/source/bayesian_imputation.ipynb
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/logistic_regression.ipynb
  notebooks/source/model_rendering.ipynb
  notebooks/source/ordinal_regression.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/contrib/optim.py
  numpyro/infer/svi.py
  numpyro/optim.py
  numpyro/version.py
  setup.py
  test/contrib/test_optim.py
  test/test_optimizers.py
Labels: awaiting review

#1297 Example: Bayes NN with steinVI
  docs/source/conf.py
  docs/source/index.rst
  examples/hmm_enum.py
  examples/hsgp.py
  examples/sparse_regression.py
  examples/stein_bnn.py
  examples/thompson_sampling.py
  notebooks/source/conf.py
  notebooks/source/time_series_forecasting.ipynb
  numpyro/compat/optim.py
  numpyro/contrib/einstein/kernels.py
  numpyro/contrib/einstein/util.py
  numpyro/distributions/continuous.py
  numpyro/distributions/directional.py
  numpyro/distributions/discrete.py
  numpyro/distributions/gof.py
  numpyro/distributions/truncated.py
  numpyro/distributions/util.py
  numpyro/examples/datasets.py
  numpyro/infer/autoguide.py
  numpyro/infer/hmc_gibbs.py
  numpyro/infer/hmc_util.py
  numpyro/infer/reparam.py
  numpyro/infer/sa.py
  test/contrib/einstein/test_einstein_util.py
  test/contrib/test_nested_sampling.py
  test/infer/test_autoguide.py
  test/infer/test_hmc_gibbs.py
  test/infer/test_hmc_util.py
  test/infer/test_infer_util.py
  test/infer/test_mcmc.py
  test/infer/test_reparam.py
  test/test_distributions.py
  test/test_examples.py
  test/test_handlers.py
Labels: awaiting review
