Repository pyro-ppl/numpyro, pull requests merged in 2024-12, with the labels that each got.

#1926 Clarify the composability of handlers with jax primities
  numpyro/handlers.py
  numpyro/infer/mcmc.py
  test/infer/test_hmc_gibbs.py
Labels: awaiting review

#1925 Add coveralls to CI
  .github/workflows/ci.yml
  README.md
  setup.py
Labels: awaiting review

#1897 Ensure BlockNeuralAutoregressiveTransform maps real->real
  numpyro/nn/block_neural_arn.py
  test/test_flows.py
Labels: awaiting response

#1930 Update coverall badge to point to the master branch
  README.md
Labels: awaiting review, easy

#1931 Add openssf badge
  README.md
Labels: awaiting review

#1936 Update link to jax repo
  README.md
  docker/release/Dockerfile
  examples/stein_dmm.py
  notebooks/source/bayesian_regression.ipynb
  notebooks/source/hsgp_nd_example.ipynb
  notebooks/source/time_series_forecasting.ipynb
  numpyro/contrib/nested_sampling.py
  numpyro/distributions/distribution.py
  numpyro/util.py
  test/test_distributions.py
Labels: awaiting review, easy

#1935 Fix tracer leak in contrib.module
  .github/workflows/ci.yml
  numpyro/contrib/module.py
  test/contrib/test_module.py
Labels: awaiting review
